"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import CopyButton from "@/components/CopyButton";
import Guestbook from "@/components/Guestbook";
import MotionSection from "@/components/motion/MotionSection";
import RSVPForm from "@/components/RSVPForm";
import { defaultSections } from "@/lib/defaultSections";
import { lisbonMedia } from "./shared";

const ink = "#123052";
const tile = "[background-image:linear-gradient(45deg,rgba(16,74,136,.1)_25%,transparent_25%),linear-gradient(-45deg,rgba(16,74,136,.1)_25%,transparent_25%),linear-gradient(45deg,transparent_75%,rgba(16,74,136,.1)_75%),linear-gradient(-45deg,transparent_75%,rgba(16,74,136,.1)_75%)] [background-position:0_0,0_12px,12px_-12px,-12px_0] [background-size:24px_24px]";

function sectionsOf(invitation: { sections?: Record<string, unknown> }) { return { ...defaultSections, ...(invitation.sections ?? {}) }; }
function first(name?: string) { return name?.trim().split(" ")[0] || ""; }
function countdown(dateValue?: string) { const target = new Date(`${dateValue || ""}T00:00:00`).getTime(); const value = Number.isNaN(target) ? 0 : Math.max(0, target - Date.now()); return [[Math.floor(value / 86_400_000), "Days"], [Math.floor((value / 3_600_000) % 24), "Hours"], [Math.floor((value / 60_000) % 60), "Minutes"], [Math.floor((value / 1_000) % 60), "Seconds"]]; }
function TileRule() { return <div className="h-2 bg-[linear-gradient(90deg,#104a88_0_12px,#f9f7f0_12px_24px,#d3a447_24px_36px,#f9f7f0_36px_48px)] bg-[length:48px_8px]" />; }

function Cover({ invitation }: TemplateProps) {
  const [opened, setOpened] = useState(false); if (opened) return null;
  const groom = first(invitation.groom_name) || "Leon"; const bride = first(invitation.bride_name) || "Mira"; const guest = invitation.guest_name?.trim() || "Dear Guest";
  const open = () => { window.dispatchEvent(new Event("invitation-opened")); setOpened(true); };
  return <section className="fixed inset-0 z-50 grid min-h-screen place-items-center overflow-hidden bg-[#e8eff7] px-5 py-7" style={{ backgroundImage: `linear-gradient(rgba(249,247,240,.48),rgba(249,247,240,.8)),url('${invitation.hero_background || lisbonMedia.hero}')`, backgroundSize: "cover", backgroundPosition: "center" }}><div className={`absolute inset-0 opacity-50 ${tile}`} /><div className="relative w-full max-w-md overflow-hidden rounded-[1.8rem] border-4 border-[#104a88] bg-[#f9f7f0] text-center shadow-2xl"><TileRule /><div className="px-8 py-10 sm:px-12 sm:py-12" style={{ color: ink }}><p className="text-[10px] font-bold uppercase tracking-[.44em] text-[#104a88]">AKSA · Lisbon Letters</p><p className="mt-8 font-serif text-xl italic">A letter of love, for</p><h1 className="mt-4 font-serif text-5xl leading-[.88] sm:text-6xl">{groom}<br /><span className="text-[#d3a447]">&amp;</span> {bride}</h1><p className="mt-6 text-[10px] font-bold uppercase tracking-[.28em] text-[#104a88]">{invitation.wedding_date || "Save the date"}</p><div className="my-8 border-y border-[#104a88]/20 py-5"><p className="text-[9px] font-bold uppercase tracking-[.34em] text-[#104a88]/65">Delivered to</p><p className="mt-2 font-serif text-2xl">{guest}</p></div><button type="button" onClick={open} className="rounded-full bg-[#104a88] px-7 py-3.5 text-xs font-bold tracking-[.17em] text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#123052]">OPEN LETTER <span className="ml-2 text-[#d3a447]">→</span></button></div><TileRule /></div></section>;
}

function Hero({ invitation }: TemplateProps) {
  const sections = sectionsOf(invitation); const [numbers, setNumbers] = useState(() => countdown(invitation.wedding_date));
  useEffect(() => { const update = () => setNumbers(countdown(invitation.wedding_date)); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [invitation.wedding_date]);
  if (!sections.hero && !sections.countdown) return null;
  const groom = first(invitation.groom_name) || "Leon"; const bride = first(invitation.bride_name) || "Mira";
  return <section className="relative z-10 overflow-hidden bg-[#f9f7f0] px-5 py-16 text-[#123052] sm:px-8 md:py-24"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-[2rem] border border-[#104a88]/25 bg-white shadow-xl md:grid-cols-[.88fr_1.12fr]"><div className={`order-2 px-8 py-12 md:order-1 md:px-12 md:py-16 ${tile}`}><div className="rounded-2xl bg-[#f9f7f0]/95 p-6 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.4em] text-[#104a88]">Postmarked with love</p>{sections.hero !== false && <><h1 className="mt-6 font-serif text-6xl leading-[.82] tracking-tight sm:text-7xl">{groom}<br /><span className="text-[#d3a447]">&amp;</span> {bride}</h1><p className="mt-7 text-sm leading-7 text-[#123052]/70">A love story written among blue tiles, old streets, and the people who make every place feel like home.</p><p className="mt-8 text-xs font-bold uppercase tracking-[.22em] text-[#104a88]">{invitation.wedding_date || "A day in Lisbon"}</p></>}</div></div><div className="relative order-1 min-h-[34rem] md:order-2"><Image src={invitation.hero_background || lisbonMedia.hero} alt="Lisbon letters" fill priority unoptimized sizes="(max-width: 768px) 100vw, 60vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#104a88]/45 to-transparent" /><p className="absolute bottom-7 left-7 text-[10px] font-bold uppercase tracking-[.35em] text-white">Lisboa · Portugal</p></div></div>{sections.countdown !== false && <div className="mx-auto mt-12 grid max-w-5xl grid-cols-4 overflow-hidden rounded-2xl border border-[#104a88]/20 bg-white py-5 text-center shadow-sm sm:py-7">{numbers.map(([value, label], index) => <div key={String(label)} className={index ? "border-l border-[#104a88]/15" : ""}><p className="font-serif text-3xl text-[#104a88] sm:text-5xl">{String(value).padStart(2, "0")}</p><p className="mt-1 text-[8px] font-bold uppercase tracking-[.18em] text-[#d3a447] sm:text-[10px]">{label}</p></div>)}</div>}</section>;
}

function Couple({ invitation }: TemplateProps) {
  if (!sectionsOf(invitation).couple) return null;
  const people = [{ role: "The groom", name: invitation.groom_name || "Leon Duarte", image: invitation.groom_cutout || invitation.groom_photo || lisbonMedia.groom, family: invitation.groom_father || invitation.groom_mother }, { role: "The bride", name: invitation.bride_name || "Mira Santos", image: invitation.bride_cutout || invitation.bride_photo || lisbonMedia.bride, family: invitation.bride_father || invitation.bride_mother }];
  return <MotionSection><section className="relative z-10 bg-[#104a88] px-5 py-20 text-white sm:px-8 md:py-28"><div className="mx-auto max-w-6xl"><div className="mb-14 text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#d3a447]">The names behind the letter</p><h2 className="mt-4 font-serif text-5xl sm:text-6xl">Two hearts, one address.</h2></div><div className="grid gap-6 md:grid-cols-2">{people.map((person) => <article key={person.role} className="overflow-hidden rounded-[1.7rem] bg-[#f9f7f0] p-4 text-[#123052] shadow-2xl"><div className="relative h-[30rem] overflow-hidden rounded-[1.25rem] bg-[radial-gradient(circle_at_50%_8%,#fffdf7,transparent_48%),linear-gradient(145deg,#bdd2eb,#f9f7f0)]"><Image src={person.image} alt={person.name} fill unoptimized sizes="(max-width: 768px) 100vw, 50vw" className="object-contain object-bottom" /></div><div className="p-4 pt-7"><p className="text-[9px] font-bold uppercase tracking-[.35em] text-[#104a88]">{person.role}</p><h3 className="mt-2 font-serif text-4xl">{person.name}</h3>{person.family && <p className="mt-3 text-sm text-[#123052]/70">Child of {person.family}</p>}</div></article>)}</div></div></section></MotionSection>;
}

function Story({ invitation }: TemplateProps) {
  const list = [[invitation.story1_year, invitation.story1_title, invitation.story1_description], [invitation.story2_year, invitation.story2_title, invitation.story2_description], [invitation.story3_year, invitation.story3_title, invitation.story3_description]].filter(([year, title, copy]) => year || title || copy); if (!sectionsOf(invitation).story || !list.length) return null;
  return <MotionSection><section className="relative z-10 bg-[#e8eff7] px-5 py-20 text-[#123052] sm:px-8 md:py-28"><div className="mx-auto max-w-5xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.42em] text-[#104a88]">Three letters home</p><h2 className="mt-4 text-center font-serif text-5xl sm:text-6xl">How we found our way.</h2><div className="mt-14 space-y-5">{list.map(([year, title, copy], index) => <article key={`${year}-${index}`} className="grid gap-5 rounded-[1.5rem] border border-[#104a88]/15 bg-[#f9f7f0] p-7 shadow-sm md:grid-cols-[7rem_1fr] md:p-9"><p className="font-serif text-4xl text-[#d3a447]">{year}</p><div><p className="text-[9px] font-bold uppercase tracking-[.28em] text-[#104a88]">Letter no. 0{index + 1}</p><h3 className="mt-3 font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-[#123052]/70">{copy}</p></div></article>)}</div></div></section></MotionSection>;
}

function ScheduleCard({ title, date, time, venue, address, maps }: { title: string; date?: string; time?: string; venue?: string; address?: string; maps?: string }) { if (!date && !time && !venue && !address) return null; return <article className="rounded-[1.5rem] bg-[#f9f7f0] p-7 text-[#123052] shadow-lg"><p className="text-[10px] font-bold uppercase tracking-[.35em] text-[#104a88]">{title}</p><h3 className="mt-6 font-serif text-3xl">{venue || title}</h3><p className="mt-6 text-sm font-bold tracking-[.12em]">{date}</p><p className="mt-2 text-sm text-[#123052]/70">{time}</p>{address && <p className="mt-5 whitespace-pre-line text-sm leading-7 text-[#123052]/70">{address}</p>}{maps && <a href={maps} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-[#104a88] px-5 py-3 text-[10px] font-bold tracking-[.15em] text-white transition hover:bg-[#d3a447]">VIEW LOCATION ↗</a>}</article>; }
function Celebration({ invitation }: TemplateProps) { if (!sectionsOf(invitation).event) return null; return <MotionSection><section className={`relative z-10 bg-[#f9f7f0] px-5 py-20 sm:px-8 md:py-28 ${tile}`}><div className="mx-auto max-w-6xl"><div className="mb-12 text-center text-[#123052]"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#104a88]">The gathering</p><h2 className="mt-4 font-serif text-5xl sm:text-6xl">Meet us in Lisbon.</h2></div><div className="grid gap-6 md:grid-cols-2"><ScheduleCard title="Ceremony" date={invitation.akad_date} time={invitation.akad_time} venue={invitation.akad_venue} address={invitation.akad_address} maps={invitation.akad_maps} /><ScheduleCard title="Reception" date={invitation.reception_date} time={invitation.reception_time} venue={invitation.reception_venue} address={invitation.reception_address} maps={invitation.reception_maps} /></div></div></section></MotionSection>; }

function LiveStream({ invitation }: TemplateProps) { const url = invitation.live_stream_url?.trim(); if (!url) return null; let embed: string | null = null; try { const parsed = new URL(url); const id = parsed.hostname.includes("youtu.be") ? parsed.pathname.slice(1) : parsed.searchParams.get("v"); embed = id ? `https://www.youtube.com/embed/${id}` : null; } catch { embed = null; } return <MotionSection><section className="relative z-10 bg-[#104a88] px-5 py-20 text-white sm:px-8 md:py-28"><div className="mx-auto max-w-4xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#d3a447]">A view from afar</p><h2 className="mt-4 font-serif text-5xl">{invitation.live_stream_title || "Join us live"}</h2><div className="mt-10 overflow-hidden rounded-[1.5rem] border border-white/20 bg-black shadow-2xl">{embed ? <div className="aspect-video"><iframe src={embed} title="Live celebration" className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : <a href={url} target="_blank" rel="noopener noreferrer" className="flex aspect-video items-center justify-center text-sm font-bold tracking-[.15em] text-[#d3a447]">WATCH THE LIVESTREAM ↗</a>}</div></div></section></MotionSection>; }

function Gallery({ invitation }: TemplateProps) { if (!sectionsOf(invitation).gallery) return null; const uploaded = invitation.gallery?.split(",").map((item: string) => item.trim()).filter(Boolean) ?? []; const positions = ["0% 0%", "100% 0%", "0% 100%", "100% 100%"]; return <MotionSection><section className="relative z-10 bg-[#f9f7f0] px-5 py-20 text-[#123052] sm:px-8 md:py-28"><div className="mx-auto max-w-6xl"><div className="mb-12 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#104a88]">The picture post</p><h2 className="mt-4 font-serif text-5xl sm:text-6xl">Postcards from Lisbon.</h2></div><p className="hidden text-[10px] font-bold uppercase tracking-[.25em] text-[#d3a447] sm:block">Blue and white memories</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{positions.map((position, index) => uploaded[index] ? <div key={uploaded[index]} className={`relative overflow-hidden rounded-[1.3rem] bg-[#dce7f2] ${index === 0 ? "col-span-2 aspect-[4/3] md:col-span-2 md:row-span-2 md:aspect-auto" : "aspect-[4/5]"}`}><Image src={uploaded[index]} alt={`Lisbon moment ${index + 1}`} fill unoptimized sizes="(max-width: 768px) 50vw, 30vw" className="object-cover transition duration-700 hover:scale-105" /></div> : <div key={position} className={`overflow-hidden rounded-[1.3rem] bg-[#dce7f2] ${index === 0 ? "col-span-2 aspect-[4/3] md:col-span-2 md:row-span-2 md:aspect-auto" : "aspect-[4/5]"}`} style={{ backgroundImage: `url('${lisbonMedia.gallerySheet}')`, backgroundPosition: position, backgroundSize: "200% 200%" }} />)}</div></div></section></MotionSection>; }

function RSVP({ invitation, guest }: TemplateProps) { if (!sectionsOf(invitation).rsvp) return null; return <MotionSection><section className="relative z-10 bg-[#dce7f2] px-5 py-20 text-[#123052] sm:px-8 md:py-28"><style>{`.lisbon-rsvp input,.lisbon-rsvp select,.lisbon-rsvp textarea{border-color:rgba(16,74,136,.34)!important;background:#f9f7f0!important;color:#123052!important;border-radius:1rem!important}.lisbon-rsvp button{background:#104a88!important;color:#fff!important;border-radius:999px!important}`}</style><div className="mx-auto max-w-4xl"><div className="mb-12 text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#104a88]">A reply, please</p><h2 className="mt-4 font-serif text-5xl sm:text-6xl">Write us back.</h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-[#123052]/70">Your presence is the most beautiful line in our story.</p></div>{invitation.is_demo ? <p className="rounded-2xl border border-[#104a88]/20 bg-[#f9f7f0] px-6 py-5 text-center text-sm leading-6">This is a live template preview. RSVP is active on your client invitation.</p> : <div className="lisbon-rsvp grid gap-12 md:grid-cols-2"><RSVPForm invitationId={invitation.id} guest={guest ?? null} /><Guestbook invitationId={invitation.id} /></div>}</div></section></MotionSection>; }

function Gift({ invitation }: TemplateProps) { const bank = invitation.bank_account?.trim(); const qris = invitation.qris_image?.trim(); const address = invitation.gift_address?.trim(); if (!sectionsOf(invitation).gift || (!bank && !qris && !address)) return null; return <MotionSection><section className="relative z-10 bg-[#f9f7f0] px-5 py-20 text-[#123052] sm:px-8 md:py-28"><div className="mx-auto max-w-5xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.42em] text-[#104a88]">With gratitude</p><h2 className="mt-4 text-center font-serif text-5xl sm:text-6xl">A thoughtful note.</h2><div className="mt-12 grid gap-6 md:grid-cols-2">{bank && <article className="rounded-[1.5rem] border border-[#104a88]/15 bg-white p-7 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#104a88]">Bank transfer</p><h3 className="mt-5 font-serif text-3xl">{invitation.bank_name || "Bank account"}</h3><p className="mt-7 text-2xl font-semibold tracking-[.08em]">{bank}</p><p className="mt-3 text-sm text-[#123052]/70">a.n. {invitation.account_name || "-"}</p><div className="mt-6"><CopyButton text={bank} /></div></article>}{qris && <article className="rounded-[1.5rem] border border-[#104a88]/15 bg-white p-7 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#104a88]">Digital payment</p><Image src={qris} alt="QRIS" width={260} height={260} className="mt-6 h-auto w-48 rounded-xl border border-[#104a88]/10 p-2" /></article>}{address && <article className="rounded-[1.5rem] border border-[#104a88]/15 bg-white p-7 shadow-sm md:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#104a88]">Send a gift</p><p className="mt-5 whitespace-pre-line text-sm leading-7 text-[#123052]/70">{address}</p></article>}</div></div></section></MotionSection>; }
function Footer({ invitation }: TemplateProps) { const groom = first(invitation.groom_name) || "Leon"; const bride = first(invitation.bride_name) || "Mira"; return <footer className="relative z-10 overflow-hidden bg-[#104a88] px-5 py-16 text-center text-white sm:px-8"><TileRule /><p className="mt-8 text-[10px] font-bold uppercase tracking-[.42em] text-[#d3a447]">Até breve</p><h2 className="mt-5 font-serif text-5xl">{groom} <span className="text-[#d3a447]">&amp;</span> {bride}</h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-white/70">Thank you for being part of the story we will always return to.</p><p className="mt-10 text-[8px] font-bold uppercase tracking-[.28em] text-white/40">Crafted by AKSA Digital Studio</p></footer>; }

export const template007: InvitationTemplate = { id: "template-007", name: "Lisbon Letters", description: "A modern Portuguese azulejo invitation in cobalt blue, white tile, and handwritten romance.", Cover, Hero, Couple, Story, Event: Celebration, LiveStream, Gallery, RSVP, Gift, Footer };
