"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, MessageCircle } from "lucide-react";
import { templateCatalog } from "@/components/TemplateGallery";

const whatsappNumber = "628133224919";
const packages = [
  { code: "digital-invitation", name: "Digital Invitation", price: "Rp199.000" },
  { code: "original-love-song", name: "Original Love Song", price: "Rp499.000" },
  { code: "ai-love-film", name: "AI Love Film", price: "From Rp1.499.000" },
];
const emptyBrief = { packageCode: "digital-invitation", eventType: "Wedding invitation", templateId: "", eventDate: "", city: "", guestCount: "", contactName: "", whatsapp: "", email: "", hosts: "", story: "", feeling: "", song: false, film: false, livestream: false, deadline: "", references: "", notes: "", consent: false };
type Brief = typeof emptyBrief;
type Props = { initialPackage?: string };

function makeMessage(brief: Brief) {
  const selectedPackage = packages.find((item) => item.code === brief.packageCode) ?? packages[0];
  const selectedTemplate = templateCatalog.find((item) => item.id === brief.templateId)?.name || "Need AKSA recommendation";
  const extras = [brief.song && "Original Love Song", brief.film && "AI Love Film", brief.livestream && "Livestream setup"].filter(Boolean).join(", ") || "None selected yet";
  return ["Hello AKSA, I have completed my order brief.", "", `Package: ${selectedPackage.name} (${selectedPackage.price})`, `Event: ${brief.eventType}`, `Template: ${selectedTemplate}`, `Event date: ${brief.eventDate || "To be confirmed"}`, `Location: ${brief.city || "To be confirmed"}`, `Guest count: ${brief.guestCount || "To be confirmed"}`, "", `Contact: ${brief.contactName}`, `WhatsApp: ${brief.whatsapp}`, `Email: ${brief.email || "Not provided"}`, `Host / couple names: ${brief.hosts || "To be confirmed"}`, "", `Story or purpose: ${brief.story || "Will share during consultation"}`, `Desired feeling: ${brief.feeling || "Need guidance"}`, `Add-ons: ${extras}`, `Desired delivery: ${brief.deadline || "Please recommend"}`, `References: ${brief.references || "None"}`, `Other notes: ${brief.notes || "None"}`, "", "Please let me know the next step and estimated timeline. Thank you."].join("\n");
}

export default function OrderBriefForm({ initialPackage }: Props) {
  const packageCode = packages.some((item) => item.code === initialPackage) ? initialPackage! : emptyBrief.packageCode;
  const [brief, setBrief] = useState<Brief>({ ...emptyBrief, packageCode });
  const [step, setStep] = useState(1); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false); const [submitting, setSubmitting] = useState(false);
  const selectedPackage = useMemo(() => packages.find((item) => item.code === brief.packageCode) ?? packages[0], [brief.packageCode]);
  const update = <K extends keyof Brief>(key: K, value: Brief[K]) => setBrief((current) => ({ ...current, [key]: value }));
  const input = "mt-2 w-full rounded-xl border border-[#19243a]/15 bg-[#fffdf9] px-4 py-3 text-sm text-[#19243a] outline-none transition placeholder:text-[#97a0af] focus:border-[#ef655a] focus:ring-4 focus:ring-[#ef655a]/10";
  const validate = (currentStep: number) => currentStep === 1 && (!brief.eventDate || !brief.city || !brief.guestCount) ? "Please complete the date, city, and guest count before continuing." : currentStep === 2 && (!brief.contactName.trim() || !brief.whatsapp.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(brief.email)) ? "Please add your name, WhatsApp, and the email you will use for your AKSA account." : currentStep === 3 && !brief.consent ? "Please confirm that AKSA may use these details to prepare your consultation." : "";
  function next() { const message = validate(step); if (message) { setError(message); return; } setError(""); setStep((value) => Math.min(3, value + 1)); }
  function previous() { setError(""); setStep((value) => Math.max(1, value - 1)); }
  async function submit() {
    const message = validate(3);
    if (message) { setError(message); return; }
    setError("");
    setSubmitting(true);
    const chat = window.open("", "_blank", "noopener,noreferrer");
    try {
      const response = await fetch("/api/order-briefs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(brief) });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.message || "We could not save your brief.");
      setSubmitted(true);
      const url = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(makeMessage(brief))}`;
      if (chat) chat.location.href = url;
      else window.open(url, "_blank", "noopener,noreferrer");
    } catch (submissionError) {
      chat?.close();
      setError(submissionError instanceof Error ? submissionError.message : "We could not save your brief. Please try again.");
    } finally {
      setSubmitting(false);
    }
  }
  return <div className="rounded-[2rem] border border-[#19243a]/10 bg-white p-5 shadow-[0_24px_70px_rgba(24,36,58,.11)] sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e26257]">Your creative brief</p><h2 className="mt-2 font-serif text-3xl text-[#19243a]">Tell us the essentials.</h2></div><span className="rounded-full bg-[#fff0ea] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#d95349]">Step {step} / 3</span></div><div className="mt-7 grid grid-cols-3 gap-2">{["Experience", "Event", "Creative direction"].map((label, index) => <div key={label}><div className={`h-1 rounded-full ${index + 1 <= step ? "bg-[#ef655a]" : "bg-[#e6e9ee]"}`} /><p className={`mt-2 text-[9px] font-bold uppercase tracking-[.1em] ${index + 1 <= step ? "text-[#19243a]" : "text-[#98a0ac]"}`}>{label}</p></div>)}</div>
    {step === 1 && <div className="mt-8 space-y-5"><label className="block text-sm font-bold text-[#19243a]">Choose your AKSA experience<select value={brief.packageCode} onChange={(event) => update("packageCode", event.target.value)} className={input}>{packages.map((item) => <option key={item.code} value={item.code}>{item.name} · {item.price}</option>)}</select></label><label className="block text-sm font-bold text-[#19243a]">What are you celebrating?<select value={brief.eventType} onChange={(event) => update("eventType", event.target.value)} className={input}>{["Wedding invitation", "Birthday celebration", "Engagement", "Family gathering", "Community / RT-RW event", "Celebration of life", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm font-bold text-[#19243a]">Template preference <span className="font-normal text-[#657087]">(optional)</span><select value={brief.templateId} onChange={(event) => update("templateId", event.target.value)} className={input}><option value="">Help me choose</option>{templateCatalog.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.label}</option>)}</select></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold text-[#19243a]">Event date<input required type="date" value={brief.eventDate} onChange={(event) => update("eventDate", event.target.value)} className={input} /></label><label className="block text-sm font-bold text-[#19243a]">Approx. guests<select value={brief.guestCount} onChange={(event) => update("guestCount", event.target.value)} className={input}><option value="">Select range</option><option>Up to 50</option><option>51–150</option><option>151–300</option><option>300+</option></select></label></div><label className="block text-sm font-bold text-[#19243a]">City / venue area<input required value={brief.city} onChange={(event) => update("city", event.target.value)} placeholder="e.g. Jakarta Selatan" className={input} /></label></div>}
    {step === 2 && <div className="mt-8 space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold text-[#19243a]">Your name<input required value={brief.contactName} onChange={(event) => update("contactName", event.target.value)} placeholder="Your full name" className={input} /></label><label className="block text-sm font-bold text-[#19243a]">WhatsApp number<input required inputMode="tel" value={brief.whatsapp} onChange={(event) => update("whatsapp", event.target.value)} placeholder="08xxxxxxxxxx" className={input} /></label></div><label className="block text-sm font-bold text-[#19243a]">AKSA account email<input required type="email" value={brief.email} onChange={(event) => update("email", event.target.value)} placeholder="you@email.com" className={input} /><span className="mt-2 block text-xs font-normal leading-5 text-[#657087]">Use this same email when creating your AKSA account. It is how we unlock your editor after payment is confirmed.</span></label><label className="block text-sm font-bold text-[#19243a]">Couple / host names <span className="font-normal text-[#657087]">(optional)</span><input value={brief.hosts} onChange={(event) => update("hosts", event.target.value)} placeholder="e.g. Aruna & Dimas" className={input} /></label><label className="block text-sm font-bold text-[#19243a]">Tell us the story or purpose <span className="font-normal text-[#657087]">(optional)</span><textarea value={brief.story} onChange={(event) => update("story", event.target.value)} rows={4} maxLength={800} placeholder="A few details about the people, moment, or message you want the invitation to carry." className={`${input} resize-none`} /></label></div>}
    {step === 3 && <div className="mt-8 space-y-6"><label className="block text-sm font-bold text-[#19243a]">Desired feeling<input value={brief.feeling} onChange={(event) => update("feeling", event.target.value)} placeholder="e.g. modern, intimate, warm, joyful" className={input} /></label><div><p className="text-sm font-bold text-[#19243a]">Interested in adding</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{[["song", "Original Love Song"], ["film", "AI Love Film"], ["livestream", "Livestream setup"]].map(([key, label]) => <label key={key} className="flex cursor-pointer items-center gap-2 rounded-xl border border-[#19243a]/10 bg-[#fffaf5] p-3 text-xs font-semibold text-[#425068]"><input type="checkbox" checked={brief[key as "song" | "film" | "livestream"]} onChange={(event) => update(key as "song" | "film" | "livestream", event.target.checked)} className="accent-[#ef655a]" />{label}</label>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold text-[#19243a]">Desired delivery <span className="font-normal text-[#657087]">(optional)</span><input type="date" value={brief.deadline} onChange={(event) => update("deadline", event.target.value)} className={input} /></label><label className="block text-sm font-bold text-[#19243a]">Reference link <span className="font-normal text-[#657087]">(optional)</span><input value={brief.references} onChange={(event) => update("references", event.target.value)} placeholder="Pinterest, Instagram, Drive, etc." className={input} /></label></div><label className="block text-sm font-bold text-[#19243a]">Anything else? <span className="font-normal text-[#657087]">(optional)</span><textarea value={brief.notes} onChange={(event) => update("notes", event.target.value)} rows={3} maxLength={600} placeholder="Accessibility needs, language, special requests, or questions." className={`${input} resize-none`} /></label><label className="flex items-start gap-3 rounded-xl bg-[#fff0ea] p-4 text-xs leading-5 text-[#68433e]"><input type="checkbox" checked={brief.consent} onChange={(event) => update("consent", event.target.checked)} className="mt-0.5 accent-[#ef655a]" /><span>I agree that AKSA may use these details to prepare my consultation and contact me about this request.</span></label><div className="rounded-xl border border-[#19243a]/10 bg-[#f7f5f0] p-4 text-sm"><p className="font-bold text-[#19243a]">Your selected experience</p><p className="mt-1 text-[#657087]">{selectedPackage.name} · {selectedPackage.price}</p></div></div>}
    {error && <p role="alert" className="mt-6 rounded-xl bg-[#fff0ea] p-3 text-sm leading-6 text-[#a33f37]">{error}</p>}{submitted && <p className="mt-6 flex gap-2 rounded-xl bg-[#e8f4ea] p-3 text-sm leading-6 text-[#367045]"><CheckCircle2 size={18} className="mt-0.5 shrink-0" />Your brief has been saved and WhatsApp is open with the complete order summary for AKSA.</p>}<div className="mt-8 flex items-center justify-between gap-3 border-t border-[#19243a]/10 pt-6">{step > 1 ? <button type="button" onClick={previous} disabled={submitting} className="inline-flex items-center gap-2 rounded-full px-4 py-3 text-sm font-bold text-[#657087] transition hover:bg-[#f7f5f0] disabled:cursor-not-allowed disabled:opacity-50"><ArrowLeft size={16} /> Back</button> : <span />}{step < 3 ? <button type="button" onClick={next} disabled={submitting} className="inline-flex items-center gap-2 rounded-full bg-[#18243a] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#18243a]/15 transition hover:bg-[#293957] disabled:cursor-not-allowed disabled:opacity-50">Continue <ArrowRight size={16} /></button> : <button type="button" onClick={submit} disabled={submitting} className="inline-flex items-center gap-2 rounded-full bg-[#ef655a] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#ef655a]/20 transition hover:bg-[#d95349] disabled:cursor-not-allowed disabled:opacity-50"><MessageCircle size={16} /> {submitting ? "Saving your brief…" : "Send brief to WhatsApp"}</button>}</div>
  </div>;
}
