"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import MotionSection from "@/components/motion/MotionSection";

type OccasionConfig = {
  id: string;
  name: string;
  description: string;
  eyebrow: string;
  coverLine: string;
  title: string;
  intro: string;
  hosts: string;
  hostNote: string;
  hero: string;
  heroAlt: string;
  place: string;
  schedule: Array<{ label: string; time: string; note: string }>;
  story: Array<{ number: string; title: string; body: string }>;
  galleryTitle: string;
  rsvpTitle: string;
  closing: string;
  colors: { paper: string; ink: string; muted: string; accent: string; dark: string; line: string; wash: string };
};

const copy = (value: unknown, fallback: string) => typeof value === "string" && value.trim() ? value : fallback;
const dateLabel = (value: unknown, fallback: string) => {
  const date = typeof value === "string" ? new Date(`${value}T00:00:00`) : null;
  return date && !Number.isNaN(date.getTime()) ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric" }).format(date) : fallback;
};
const remaining = (value: unknown) => {
  const time = typeof value === "string" ? new Date(`${value}T00:00:00`).getTime() : 0;
  const distance = Number.isNaN(time) ? 0 : Math.max(0, time - Date.now());
  return [[Math.floor(distance / 86400000), "Days"], [Math.floor(distance / 3600000) % 24, "Hours"], [Math.floor(distance / 60000) % 60, "Minutes"], [Math.floor(distance / 1000) % 60, "Seconds"]] as const;
};

function useCountdown(date: unknown) {
  const [clock, setClock] = useState(() => remaining(date));
  useEffect(() => { const timer = window.setInterval(() => setClock(remaining(date)), 1000); return () => window.clearInterval(timer); }, [date]);
  return clock;
}

function Rule({ color }: { color: string }) { return <span aria-hidden="true" className="h-px w-10" style={{ background: color }} />; }

function createOccasionTemplate(config: OccasionConfig): InvitationTemplate {
  const Cover = ({ invitation }: TemplateProps) => {
    const [open, setOpen] = useState(false);
    if (open) return null;
    return <section className="fixed inset-0 z-50 grid place-items-center overflow-hidden p-5 text-center" style={{ background: config.colors.dark, color: config.colors.paper }}><Image src={config.hero} alt="" fill priority unoptimized className="object-cover opacity-35" /><div className="absolute inset-0 bg-black/25" /><div className="relative w-full max-w-md border p-3 shadow-2xl" style={{ borderColor: config.colors.line }}><div className="min-h-[34rem] border p-8" style={{ borderColor: config.colors.line }}><div className="flex items-center justify-center gap-3 text-[9px] font-bold uppercase tracking-[.3em]"><Rule color={config.colors.accent} />{config.eyebrow}<Rule color={config.colors.accent} /></div><div className="mt-28"><p className="text-[10px] uppercase tracking-[.28em] text-white/70">{config.coverLine}</p><h1 className="mt-5 font-serif text-6xl leading-[.85]">{config.title}</h1><p className="mx-auto mt-6 max-w-xs text-sm leading-6 text-white/75">{config.intro}</p></div><div className="mt-24"><p className="text-[10px] font-bold uppercase tracking-[.22em]">{dateLabel(invitation.wedding_date, "A beautiful day ahead")}</p><button onClick={() => { window.dispatchEvent(new Event("invitation-opened")); setOpen(true); }} className="mt-7 w-full px-6 py-4 text-[10px] font-bold uppercase tracking-[.2em] transition hover:opacity-85" style={{ background: config.colors.paper, color: config.colors.ink }}>Open invitation</button></div></div></div></section>;
  };

  const Hero = ({ invitation }: TemplateProps) => {
    const clock = useCountdown(invitation.wedding_date);
    const date = dateLabel(invitation.wedding_date, "Coming soon");
    return <section className="relative z-10 overflow-hidden px-5 py-20 sm:px-8" style={{ background: config.colors.paper, color: config.colors.ink }}><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div className="order-2 lg:order-1"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>{config.eyebrow}</p><h1 className="mt-5 font-serif text-6xl leading-[.84] tracking-[-.04em] sm:text-8xl">{config.title}</h1><p className="mt-7 max-w-md text-base leading-8" style={{ color: config.colors.muted }}>{config.intro}</p><p className="mt-9 border-l pl-4 text-[10px] font-bold uppercase tracking-[.22em]" style={{ borderColor: config.colors.accent }}>{date} · {copy(invitation.akad_venue, config.place)}</p></div><div className="order-1 border p-3 lg:order-2" style={{ borderColor: config.colors.line, background: config.colors.wash }}><div className="relative aspect-[4/5] overflow-hidden"><Image src={copy(invitation.hero_background, config.hero)} alt={config.heroAlt} fill priority unoptimized className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent" /><p className="absolute bottom-5 left-5 text-[10px] font-bold uppercase tracking-[.24em] text-white">AKSA · {config.name}</p></div></div></div><div className="mx-auto mt-14 grid max-w-6xl grid-cols-2 border-l border-t sm:grid-cols-4" style={{ borderColor: config.colors.line }}>{clock.map(([value, label]) => <div key={label} className="border-b border-r p-5 text-center" style={{ borderColor: config.colors.line, background: config.colors.wash }}><p className="font-serif text-4xl">{String(value).padStart(2, "0")}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.16em]" style={{ color: config.colors.muted }}>{label}</p></div>)}</div></section>;
  };

  const Couple = ({ invitation }: TemplateProps) => <MotionSection><section className="relative z-10 px-5 py-20 sm:px-8" style={{ background: config.colors.wash, color: config.colors.ink }}><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative aspect-[4/5] overflow-hidden border-[12px] shadow-xl" style={{ borderColor: config.colors.paper }}><Image src={copy(invitation.hero_background, config.hero)} alt={config.heroAlt} fill unoptimized className="object-cover" /></div><div><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>The people behind it</p><h2 className="mt-5 font-serif text-5xl leading-[.9] sm:text-6xl">{copy(invitation.groom_name, config.hosts)}</h2>{invitation.bride_name && <p className="mt-2 font-serif text-3xl" style={{ color: config.colors.accent }}>{invitation.bride_name}</p>}<p className="mt-8 max-w-lg text-base leading-8" style={{ color: config.colors.muted }}>{copy(invitation.story1_description, config.hostNote)}</p><p className="mt-10 border-t pt-4 text-[10px] font-bold uppercase tracking-[.2em]" style={{ borderColor: config.colors.line }}>{config.coverLine}</p></div></div></section></MotionSection>;

  const Story = () => <MotionSection><section className="relative z-10 px-5 py-20 sm:px-8" style={{ background: config.colors.paper, color: config.colors.ink }}><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>The feeling</p><h2 className="mt-5 font-serif text-5xl">A celebration with intention.</h2><div className="mt-12 grid border-l border-t md:grid-cols-3" style={{ borderColor: config.colors.line }}>{config.story.map((item) => <article key={item.number} className="min-h-64 border-b border-r p-7" style={{ borderColor: config.colors.line, background: config.colors.wash }}><p className="text-[10px] font-bold tracking-[.2em]" style={{ color: config.colors.accent }}>{item.number}</p><h3 className="mt-12 font-serif text-3xl">{item.title}</h3><p className="mt-5 text-sm leading-7" style={{ color: config.colors.muted }}>{item.body}</p></article>)}</div></div></section></MotionSection>;

  const EventDetails = ({ invitation }: TemplateProps) => <MotionSection><section className="relative z-10 px-5 py-20 sm:px-8" style={{ background: config.colors.dark, color: config.colors.paper }}><div className="mx-auto max-w-5xl"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>Save the date</p><h2 className="mt-5 font-serif text-5xl">The details.</h2><div className="mt-12 grid gap-4 md:grid-cols-2">{config.schedule.map((item, index) => <article key={item.label} className="border p-7" style={{ borderColor: config.colors.line }}><p className="text-[10px] font-bold uppercase tracking-[.24em]" style={{ color: config.colors.accent }}>0{index + 1} · {item.label}</p><h3 className="mt-10 font-serif text-3xl">{index === 0 ? copy(invitation.akad_venue, config.place) : copy(invitation.reception_venue, config.place)}</h3><div className="mt-7 border-y py-4 text-sm" style={{ borderColor: config.colors.line }}><p>{dateLabel(invitation.wedding_date, "To be confirmed")}</p><p className="mt-2 text-white/70">{index === 0 ? copy(invitation.akad_time, item.time) : copy(invitation.reception_time, item.time)}</p></div><p className="mt-5 whitespace-pre-line text-sm leading-7 text-white/70">{index === 0 ? copy(invitation.akad_address, item.note) : copy(invitation.reception_address, item.note)}</p></article>)}</div></div></section></MotionSection>;

  const Gallery = () => <MotionSection><section className="relative z-10 px-5 py-20 sm:px-8" style={{ background: config.colors.paper, color: config.colors.ink }}><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>A visual note</p><h2 className="mt-5 font-serif text-5xl">{config.galleryTitle}</h2><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4"><div className="relative col-span-2 aspect-[4/3] overflow-hidden"><Image src={config.hero} alt={config.heroAlt} fill unoptimized className="object-cover" /></div><div className="aspect-[4/5] p-5" style={{ background: config.colors.accent }}><div className="h-full border border-white/60" /></div><div className="aspect-[4/5] p-5" style={{ background: config.colors.wash }}><div className="flex h-full items-end border p-4 font-serif text-2xl" style={{ borderColor: config.colors.line }}>Made for<br />your moment.</div></div></div></div></section></MotionSection>;

  const RSVP = () => <MotionSection><section className="relative z-10 px-5 py-20 sm:px-8" style={{ background: config.colors.wash, color: config.colors.ink }}><div className="mx-auto max-w-4xl"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{ color: config.colors.accent }}>Please reply</p><h2 className="mt-5 font-serif text-5xl">{config.rsvpTitle}</h2><div className="mt-10 grid gap-4 md:grid-cols-[1.2fr_.8fr]"><div className="border p-7" style={{ borderColor: config.colors.line, background: config.colors.paper }}><p className="text-sm leading-7" style={{ color: config.colors.muted }}>Every AKSA invitation includes a personal RSVP experience, guest count, and a thoughtful confirmation flow.</p><div className="mt-8 flex gap-3"><span className="rounded-full px-4 py-3 text-xs font-bold text-white" style={{ background: config.colors.dark }}>I&apos;ll be there</span><span className="rounded-full border px-4 py-3 text-xs font-bold" style={{ borderColor: config.colors.line }}>Send regards</span></div></div><div className="border p-7" style={{ borderColor: config.colors.line }}><p className="text-[10px] font-bold uppercase tracking-[.2em]" style={{ color: config.colors.accent }}>AKSA event pass</p><p className="mt-5 font-serif text-3xl">Arrival, made simple.</p><p className="mt-4 text-sm leading-6" style={{ color: config.colors.muted }}>Optional QR check-in is ready for celebrations that welcome a crowd.</p></div></div></div></section></MotionSection>;

  const Gift = () => null;
  const Footer = () => <footer className="relative z-10 px-5 py-16 text-center" style={{ background: config.colors.dark, color: config.colors.paper }}><p className="text-[10px] font-bold uppercase tracking-[.3em]" style={{ color: config.colors.accent }}>AKSA Digital Studio · {config.name}</p><h2 className="mx-auto mt-5 max-w-xl font-serif text-5xl">{config.closing}</h2></footer>;

  return { id: config.id, name: config.name, description: config.description, thumbnail: config.hero, Cover, Hero, Couple, Story, Event: EventDetails, Gallery, RSVP, Gift, Footer };
}

export const template018 = createOccasionTemplate({ id: "template-018", name: "Petal & Promise", description: "A sunlit garden engagement invitation of ivory linen, peonies, and champagne.", eyebrow: "Engagement invitation", coverLine: "A promise in bloom", title: "Petal & Promise", intro: "A warm garden gathering to celebrate the beginning of something beautiful.", hosts: "Aruna & Dimas", hostNote: "A small yes, a long-awaited celebration, and the people who have made every season feel like home.", hero: "/template-demos/engagement-petal-promise/hero.png", heroAlt: "Garden engagement celebration", place: "The Garden House", schedule: [{ label: "Welcome toast", time: "15:30 WIB", note: "A gentle afternoon among flowers, stories, and champagne." }, { label: "Family dinner", time: "18:00 WIB", note: "An intimate table shared with the people we love." }], story: [{ number: "01", title: "A familiar beginning", body: "The kind of conversation that makes an ordinary day feel quietly different." }, { number: "02", title: "The question", body: "One gentle promise, made beneath a garden full of light." }, { number: "03", title: "The gathering", body: "A moment made brighter by every person who has loved us along the way." }], galleryTitle: "A garden, a promise, a beginning.", rsvpTitle: "Save us a place in your afternoon.", closing: "A promise, beautifully shared.", colors: { paper: "#fffaf3", ink: "#3d4033", muted: "#6d7161", accent: "#bd766e", dark: "#374236", line: "#d6c5b8", wash: "#f2e4dc" } });

export const template019 = createOccasionTemplate({ id: "template-019", name: "Tiny Star", description: "A refined first birthday invitation of buttercream, paper stars, and soft garden light.", eyebrow: "Birthday invitation", coverLine: "One small star, one big celebration", title: "Tiny Star", intro: "A sweet afternoon celebrating a very loved little person and their first bright year.", hosts: "Mika turns one", hostNote: "One year of small discoveries, soft mornings, and more joy than we ever imagined.", hero: "/template-demos/birthday-tiny-star/hero.png", heroAlt: "Luxury first birthday garden table", place: "The Little Garden", schedule: [{ label: "Cake & play", time: "15:00 WIB", note: "A soft afternoon of cake, garden games, and tiny discoveries." }, { label: "Family supper", time: "17:30 WIB", note: "A simple shared table for family and our closest friends." }], story: [{ number: "01", title: "One tiny hello", body: "A year ago, the world became softer, louder, and so much more joyful." }, { number: "02", title: "Little discoveries", body: "Every day brought a new look, a new laugh, and a new reason to pause." }, { number: "03", title: "A full heart", body: "We are gathering the people who have loved this little life from the start." }], galleryTitle: "Small details. Big joy.", rsvpTitle: "Come celebrate our tiny star.", closing: "One bright year, beautifully remembered.", colors: { paper: "#fffdf4", ink: "#344954", muted: "#65757a", accent: "#ba9750", dark: "#385365", line: "#d7cda9", wash: "#e8f0ec" } });

export const template020 = createOccasionTemplate({ id: "template-020", name: "Studio Session", description: "A blue-hour gathering invitation with warm hospitality, thoughtful details, and modern clarity.", eyebrow: "Event invitation", coverLine: "An evening to gather", title: "Studio Session", intro: "A welcoming night for conversation, new ideas, and a shared table under the courtyard lights.", hosts: "AKSA Community", hostNote: "We are bringing friends, neighbours, and good ideas together for one generous evening in the city.", hero: "/template-demos/event-studio-session/hero.png", heroAlt: "Candlelit community event courtyard", place: "The Courtyard House", schedule: [{ label: "Doors open", time: "18:30 WIB", note: "Settle in, meet someone new, and take your place at the table." }, { label: "Shared session", time: "19:30 WIB", note: "A relaxed programme of stories, ideas, dinner, and conversation." }], story: [{ number: "01", title: "Open the door", body: "The best gatherings leave room for new people, unexpected conversations, and a little curiosity." }, { number: "02", title: "Share the table", body: "Thoughtful food and honest ideas make a good reason to stay a little longer." }, { number: "03", title: "Take it forward", body: "We hope the evening leaves every guest with a new connection and a bright next step." }], galleryTitle: "The atmosphere sets the tone.", rsvpTitle: "Reserve your place at the table.", closing: "A good gathering starts with an invitation.", colors: { paper: "#f8f2e8", ink: "#17273d", muted: "#576575", accent: "#d39a53", dark: "#18283f", line: "#b8a48b", wash: "#e7ded0" } });
