"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import CopyButton from "@/components/CopyButton";
import Guestbook from "@/components/Guestbook";
import MotionSection from "@/components/motion/MotionSection";
import RSVPForm from "@/components/RSVPForm";
import { defaultSections } from "@/lib/defaultSections";

const bhaktiAssets = { hero: "/template-demos/template-004/hero.webp", groom: "/template-demos/template-004/groom.webp", bride: "/template-demos/template-004/bride.webp", gallery: ["/template-demos/template-004/gallery-1.webp", "/template-demos/template-004/gallery-2.webp", "/template-demos/template-004/gallery-3.webp"] };
const sectionsFor = (invitation: { sections?: Record<string, unknown> }) => ({ ...defaultSections, ...(invitation.sections ?? {}) });
const firstName = (value?: string) => value?.trim().split(" ")[0] || "";
const initials = (invitation: TemplateProps["invitation"]) => `${firstName(invitation.groom_name).slice(0, 1) || "D"}${firstName(invitation.bride_name).slice(0, 1) || "K"}`;

function countdownFor(date?: string) { const target = new Date(`${date || ""}T00:00:00`).getTime(); const remaining = Number.isNaN(target) ? 0 : Math.max(0, target - Date.now()); return [[Math.floor(remaining / 86400000), "Days"], [Math.floor(remaining / 3600000) % 24, "Hours"], [Math.floor(remaining / 60000) % 60, "Minutes"], [Math.floor(remaining / 1000) % 60, "Seconds"]]; }
function useCountdown(date?: string) { const [values, setValues] = useState(() => countdownFor(date)); useEffect(() => { const timer = window.setInterval(() => setValues(countdownFor(date)), 1000); return () => window.clearInterval(timer); }, [date]); return values; }
function TrustMark({ className = "" }: { className?: string }) { return <span aria-hidden="true" className={`inline-flex items-center gap-2 text-[11px] tracking-[.3em] ${className}`}>◆ ◇ ◆</span>; }
function BlueGrid({ className = "" }: { className?: string }) { return <div aria-hidden="true" className={`pointer-events-none absolute ${className}`} style={{ backgroundImage: "linear-gradient(90deg,currentColor 1px,transparent 1px),linear-gradient(currentColor 1px,transparent 1px)", backgroundSize: "26px 26px" }} />; }

function Cover({ invitation }: TemplateProps) { const [opened, setOpened] = useState(false); if (opened) return null; return <section className="fixed inset-0 z-50 grid place-items-center overflow-hidden bg-[#071d36] px-5 py-8 text-[#f7fafc]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_-10%,#2c6aa4_0%,#0b2d51_42%,#051426_100%)]" /><BlueGrid className="inset-0 text-[#8ed1ee]/10" /><div className="relative w-full max-w-md border border-[#b8ceda]/60 bg-[#0e365f]/90 p-2 shadow-2xl"><div className="relative overflow-hidden border border-[#dce7ed]/50 px-7 py-12 text-center sm:px-10"><div className="absolute inset-x-0 top-0 h-2 bg-[#51b7df]" /><TrustMark className="relative text-[#bce6f4]" /><p className="relative mt-7 text-[10px] font-bold uppercase tracking-[.42em] text-[#dce7ed]">AKSA · Bhakti Biru</p><div className="relative mx-auto mt-8 grid h-24 w-24 place-items-center rounded-full border-2 border-[#bce6f4] bg-[#eaf2f4] font-serif text-3xl text-[#143b64] shadow-[0_0_0_8px_rgba(81,183,223,.14)]">{initials(invitation)}</div><p className="relative mt-8 text-[10px] font-bold uppercase tracking-[.28em] text-white/65">A ceremony of trust and love</p><h1 className="relative mt-5 font-serif text-5xl leading-[.9] sm:text-6xl">{firstName(invitation.groom_name) || "Dimas"}<br /><span className="italic text-[#bce6f4]">&amp;</span> {firstName(invitation.bride_name) || "Kayla"}</h1><p className="relative mt-8 text-[10px] font-bold uppercase tracking-[.25em] text-white/70">The blue hour · {invitation.wedding_date}</p><button onClick={() => { window.dispatchEvent(new Event("invitation-opened")); setOpened(true); }} className="relative mt-9 bg-[#bce6f4] px-7 py-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#11385f] transition hover:bg-white">Open invitation</button></div></div></section>; }

function Hero({ invitation }: TemplateProps) { const sections = sectionsFor(invitation); const countdown = useCountdown(invitation.wedding_date); if (!sections.hero && !sections.countdown) return null; return <section className="relative z-10 overflow-hidden bg-[#071d36] px-5 py-20 text-[#f7fafc] sm:px-8 sm:py-28"><BlueGrid className="inset-0 text-[#8ed1ee]/10" /><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.9fr_1fr] lg:items-center"><div className="text-center lg:text-left"><TrustMark className="text-[#bce6f4]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.42em] text-[#dce7ed]">A new chapter in blue</p><h1 className="mt-6 font-serif text-6xl leading-[.82] tracking-[-.04em] sm:text-8xl">{firstName(invitation.groom_name) || "Dimas"}<br /><span className="italic text-[#bce6f4]">&amp;</span> {firstName(invitation.bride_name) || "Kayla"}</h1><p className="mx-auto mt-9 max-w-md text-base leading-8 text-white/70 lg:mx-0">With trust as our compass and our loved ones beside us, we begin the most meaningful journey of all.</p><p className="mt-9 border-l-2 border-[#51b7df] pl-4 text-[10px] font-bold uppercase tracking-[.25em] text-[#dce7ed]">The blue hour · {invitation.wedding_date}</p></div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 rounded-[1.5rem] border border-[#bce6f4]/50" /><div className="relative aspect-[4/5] overflow-hidden rounded-[1.25rem] bg-[#1f5b91] shadow-[18px_18px_0_rgba(81,183,223,.22)]"><Image src={invitation.hero_background || bhaktiAssets.hero} alt="Bhakti Biru wedding celebration" fill priority unoptimized className="object-cover mix-blend-luminosity opacity-80" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(3,31,62,.04),rgba(3,31,62,.68))]" /><TrustMark className="absolute bottom-7 left-1/2 -translate-x-1/2 text-[#dce7ed]" /></div><div className="absolute -bottom-7 -left-4 grid h-28 w-28 place-items-center rounded-full border-8 border-[#071d36] bg-[#bce6f4] font-serif text-3xl text-[#143b64] shadow-xl">{initials(invitation)}</div></div></div>{sections.countdown !== false && <div className="relative mx-auto mt-20 grid max-w-5xl grid-cols-2 gap-3 sm:grid-cols-4">{countdown.map(([value, label]) => <div key={String(label)} className="border border-[#bce6f4]/45 bg-[#0d3158]/85 py-7 text-center"><p className="font-serif text-4xl text-[#dce7ed]">{String(value).padStart(2, "0")}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.2em] text-white/60">{label}</p></div>)}</div>}</section>; }

function Couple({ invitation }: TemplateProps) { if (!sectionsFor(invitation).couple) return null; const groom = invitation.groom_cutout || invitation.groom_photo || bhaktiAssets.groom; const bride = invitation.bride_cutout || invitation.bride_photo || bhaktiAssets.bride; return <MotionSection><section className="relative z-10 overflow-hidden bg-[#f2f5f4] px-5 py-20 text-[#12375e] sm:px-8"><BlueGrid className="inset-0 text-[#143b64]/7" /><div className="relative mx-auto max-w-6xl"><div className="max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#3073ad]">Two lives, one promise</p><h2 className="mt-4 font-serif text-5xl">A partnership of care.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2">{[["The groom", invitation.groom_name || "Dimas Pradana", groom], ["The bride", invitation.bride_name || "Kayla Anindita", bride]].map(([role, name, image]) => <article key={String(role)} className="relative border border-[#b8ceda] bg-white p-4 shadow-[10px_10px_0_rgba(18,55,94,.1)]"><div className="absolute inset-x-4 top-4 h-2 bg-[#51b7df]" /><div className="relative mt-3 h-[29rem] overflow-hidden bg-[#a8c4d8]"><Image src={String(image)} alt={String(name)} fill unoptimized className="object-cover object-top" /><div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-[#12375e]/75 to-transparent" /></div><p className="mt-5 text-[9px] font-bold uppercase tracking-[.28em] text-[#3073ad]">{role}</p><h3 className="mt-2 font-serif text-4xl">{name}</h3></article>)}</div></div></section></MotionSection>; }

function Story({ invitation }: TemplateProps) { const stories = [[invitation.story1_year, invitation.story1_title, invitation.story1_description], [invitation.story2_year, invitation.story2_title, invitation.story2_description], [invitation.story3_year, invitation.story3_title, invitation.story3_description]].filter((story) => story.some(Boolean)); if (!sectionsFor(invitation).story || !stories.length) return null; return <MotionSection><section className="relative z-10 bg-[#12375e] px-5 py-20 text-[#f7fafc] sm:px-8"><BlueGrid className="inset-0 text-[#bce6f4]/10" /><div className="relative mx-auto max-w-6xl"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#bce6f4]">The story we trust</p><h2 className="mt-4 font-serif text-5xl">Every moment made us stronger.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{stories.map(([year, title, description], index) => <article key={`${year}-${title}`} className="relative overflow-hidden border border-[#bce6f4]/45 bg-[#0d3158]/80 p-7"><p className="text-[9px] font-bold uppercase tracking-[.25em] text-[#bce6f4]">Chapter 0{index + 1} · {year}</p><div className="mt-5 h-px w-14 bg-[#51b7df]" /><h3 className="mt-5 font-serif text-3xl">{title}</h3><p className="mt-5 text-sm leading-7 text-white/70">{description}</p></article>)}</div></div></section></MotionSection>; }

function ScheduleCard({ title, date, time, venue, address, map }: { title: string; date?: string; time?: string; venue?: string; address?: string; map?: string }) { return <article className="relative overflow-hidden border border-[#b8ceda] bg-white p-8 text-center shadow-sm"><div className="absolute inset-x-0 top-0 h-2 bg-[#51b7df]" /><TrustMark className="text-[#3073ad]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.28em] text-[#3073ad]">{title}</p><h3 className="mt-6 font-serif text-3xl text-[#12375e]">{venue || title}</h3><div className="mt-7 border-y border-dashed border-[#9abbd2] py-4 text-sm text-[#5b7185]"><p className="font-bold text-[#12375e]">{date}</p><p className="mt-2">{time}</p></div><p className="mt-6 whitespace-pre-line text-sm leading-7 text-[#5b7185]">{address}</p>{map && <a href={map} target="_blank" rel="noreferrer" className="mt-6 inline-block border-b border-[#12375e] pb-1 text-[10px] font-bold uppercase tracking-[.16em] text-[#12375e]">Find the celebration ↗</a>}</article>; }
function FormalProgramme({ invitation }: TemplateProps) { if (!sectionsFor(invitation).event) return null; return <MotionSection><section className="relative z-10 bg-[#f2f5f4] px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl"><div className="text-center text-[#12375e]"><TrustMark className="text-[#3073ad]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.42em] text-[#3073ad]">The formal programme</p><h2 className="mt-4 font-serif text-5xl">Celebrate with us.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2"><ScheduleCard title="The vows" date={invitation.akad_date} time={invitation.akad_time} venue={invitation.akad_venue} address={invitation.akad_address} map={invitation.akad_maps} /><ScheduleCard title="The reception" date={invitation.reception_date} time={invitation.reception_time} venue={invitation.reception_venue} address={invitation.reception_address} map={invitation.reception_maps} /></div></div></section></MotionSection>; }
function LiveStream({ invitation }: TemplateProps) { const url = invitation.live_stream_url?.trim(); if (!url && !invitation.is_demo) return null; return <MotionSection><section className="relative z-10 bg-[#071d36] px-5 py-20 text-[#f7fafc] sm:px-8"><div className="mx-auto max-w-4xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#bce6f4]">Share the moment</p><h2 className="mt-4 font-serif text-5xl">{invitation.live_stream_title || "Join our ceremony, live."}</h2><div className="mt-10 grid aspect-video place-items-center border border-[#bce6f4]/55 bg-[#0d3158]"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-[#bce6f4] pl-1 text-xl text-[#bce6f4]">▶</span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.28em]">A moment of connection</p>{url && <a href={url} target="_blank" rel="noreferrer" className="mt-5 inline-block border-b border-[#bce6f4] pb-1 text-xs text-[#dce7ed]">Open live stream ↗</a>}</div></div></div></section></MotionSection>; }
function Gallery({ invitation }: TemplateProps) { if (!sectionsFor(invitation).gallery) return null; const uploaded = invitation.gallery?.split(",").map((item: string) => item.trim()).filter(Boolean) || []; const images = uploaded.length ? uploaded : [bhaktiAssets.gallery[0], bhaktiAssets.gallery[1], bhaktiAssets.gallery[2], invitation.hero_background || bhaktiAssets.hero]; return <MotionSection><section className="relative z-10 bg-[#e3ebed] px-5 py-20 text-[#12375e] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#3073ad]">The blue album</p><h2 className="mt-4 font-serif text-5xl">A day we will always remember.</h2><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">{images.slice(0, 4).map((image: string, index: number) => <div key={`${image}-${index}`} className={`relative overflow-hidden border-4 border-white bg-[#143b64] shadow-sm ${index === 0 ? "col-span-2 aspect-[4/3] md:row-span-2 md:aspect-auto" : "aspect-[4/5]"}`}><Image src={image} alt="Bhakti Biru wedding moment" fill unoptimized className="object-cover transition duration-700 hover:scale-105" /></div>)}</div></div></section></MotionSection>; }
function RSVP({ invitation, guest }: TemplateProps) { if (!sectionsFor(invitation).rsvp) return null; return <MotionSection><section className="relative z-10 bg-[#f2f5f4] px-5 py-20 text-[#12375e] sm:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><TrustMark className="text-[#3073ad]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.42em] text-[#3073ad]">Your place in our story</p><h2 className="mt-4 font-serif text-5xl">RSVP</h2></div>{invitation.is_demo ? <p className="mx-auto mt-12 max-w-xl border border-dashed border-[#9abbd2] bg-white p-7 text-center text-sm leading-7 text-[#5b7185]">Your personal RSVP confirmation will appear here once this invitation is published.</p> : <div className="mt-12 grid gap-10 md:grid-cols-2"><RSVPForm invitationId={invitation.id} guest={guest ?? null} /><Guestbook invitationId={invitation.id} /></div>}</div></section></MotionSection>; }
function Gift({ invitation }: TemplateProps) { if (!sectionsFor(invitation).gift || !invitation.bank_account) return null; return <section className="relative z-10 bg-[#12375e] px-5 py-20 text-[#f7fafc]"><div className="mx-auto max-w-xl border border-[#bce6f4]/60 bg-[#0d3158] p-10 text-center"><TrustMark className="text-[#bce6f4]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.42em] text-[#bce6f4]">With gratitude</p><h2 className="mt-4 font-serif text-4xl">A generous blessing.</h2><p className="mt-8 font-serif text-2xl">{invitation.bank_name}</p><p className="mt-3 text-lg">{invitation.bank_account}</p><div className="mt-6"><CopyButton text={invitation.bank_account} /></div></div></section>; }
function Footer({ invitation }: TemplateProps) { return <footer className="relative z-10 overflow-hidden bg-[#051426] px-5 py-16 text-center text-[#f7fafc]"><BlueGrid className="inset-0 text-[#bce6f4]/10" /><div className="relative"><TrustMark className="text-[#bce6f4]" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.42em] text-[#bce6f4]">Bhakti Biru</p><h2 className="mt-5 font-serif text-5xl">{firstName(invitation.groom_name) || "Dimas"} <span className="italic text-[#bce6f4]">&amp;</span> {firstName(invitation.bride_name) || "Kayla"}</h2><p className="mt-8 text-[10px] uppercase tracking-[.32em] text-white/55">AKSA Digital Studio · A ceremony of trust and love</p></div></footer>; }

export const template025: InvitationTemplate = { id: "template-025", name: "Bhakti Biru", description: "A modern midnight-blue, silver, and ivory wedding invitation inspired by service, trust, and commitment. It uses no official police insignia.", Cover, Hero, Couple, Story, Event: FormalProgramme, LiveStream, Gallery, RSVP, Gift, Footer };
