"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CirclePlay, Film, Headphones, MessageCircle, Plus, Quote, Sparkles } from "lucide-react";

const whatsappNumber = "628133224919";
const whatsappUrl = (message: string) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

const portfolio = [
  { title: "Side A, Side B", label: "Music invitation", description: "A vinyl-inspired wedding world with tracklist storytelling and an after-dark pulse.", image: "/template-demos/template-014/side-a-hero.png", href: "/templates/template-014", accent: "#f3c777" },
  { title: "Riad After Dark", label: "Destination celebration", description: "Emerald tiles, brass light, and a courtyard romance made for an immersive RSVP journey.", image: "/template-demos/template-016/riad-hero.png", href: "/templates/template-016", accent: "#c99c52" },
  { title: "Copenhagen Quiet", label: "Modern editorial", description: "Pale stone, walnut, and restrained type for a creative couple who value calm details.", image: "/template-demos/template-017/copenhagen-hero.png", href: "/templates/template-017", accent: "#8c765d" },
];

const faqs = [
  ["Can I explore templates before paying?", "Yes. Every public AKSA template can be explored freely. Your private workspace, editor, uploads, and publishing tools unlock once AKSA confirms payment."],
  ["Do I need an AKSA account?", "Yes, when you are ready to make an invitation. Use the same email as the order brief so AKSA can unlock the correct workspace after payment."],
  ["Can AKSA create invitations beyond weddings?", "Yes. AKSA can shape birthdays, engagements, family celebrations, community events, corporate gatherings, and meaningful memorial invitations."],
  ["How does the Original Love Song work?", "You share the story, feeling, and moments that matter. AKSA develops a custom musical direction, then prepares the song as part of your invitation experience."],
  ["What is included in an AI Love Film?", "It is a creative visual treatment built around the couple’s story, references, and selected direction. Scope, turnaround, and revision rounds are confirmed before production."],
  ["Can I still make changes after publishing?", "Yes. Your active paid workspace stays editable. Save your changes in the studio and your invitation updates without changing its shareable link."],
];

export default function LandingProofSections() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  return <>
    <section id="portfolio" className="bg-[#fffaf5] px-5 py-20 sm:px-6 lg:px-10 lg:py-28">
      <div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#d95349]">Live portfolio</p><h2 className="mt-4 font-serif text-4xl leading-[.96] tracking-[-.035em] sm:text-5xl">See the feeling<br /><span className="text-[#9aa2ad]">before you choose it.</span></h2><p className="mt-5 max-w-xl text-sm leading-7 text-[#5c677d]">These are real, interactive AKSA invitation worlds—not static mockups. Open them, scroll through the story, and feel how every detail works together.</p></div><Link href="/templates" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-[#18243a] hover:text-[#d95349]">Explore every live template <ArrowRight size={16} /></Link></div>
        <div className="mt-12 grid gap-5 lg:grid-cols-3">{portfolio.map((item) => <Link key={item.title} href={item.href} className="group overflow-hidden rounded-[1.75rem] border border-[#18243a]/10 bg-white shadow-[0_16px_42px_rgba(24,36,58,.08)] transition duration-300 hover:-translate-y-2 hover:shadow-[0_24px_56px_rgba(24,36,58,.16)]"><div className="relative aspect-[1.2]"><Image src={item.image} alt={`${item.title} invitation preview`} fill className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#13203a]/85 via-[#13203a]/5 to-transparent" /><span className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-2 text-[9px] font-bold uppercase tracking-[.16em] text-[#18243a] backdrop-blur">Live experience</span><div className="absolute inset-x-5 bottom-5"><p className="text-[10px] font-bold uppercase tracking-[.2em]" style={{ color: item.accent }}>{item.label}</p><h3 className="mt-2 font-serif text-3xl text-white">{item.title}</h3></div></div><div className="flex items-start justify-between gap-4 p-5"><p className="text-sm leading-6 text-[#657087]">{item.description}</p><ArrowRight className="mt-1 shrink-0 text-[#e26257]" size={18} /></div></Link>)}</div>
      </div>
    </section>

    <section id="originals" className="relative overflow-hidden bg-[#14233c] px-5 py-20 text-white sm:px-6 lg:px-10 lg:py-28"><div className="absolute -left-24 top-12 h-80 w-80 rounded-full bg-[#e96257]/20 blur-3xl" /><div className="absolute -right-28 bottom-0 h-96 w-96 rounded-full bg-[#74bdd2]/20 blur-3xl" /><div className="relative mx-auto max-w-7xl"><div className="max-w-2xl"><p className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.25em] text-[#f4cf6c]"><Sparkles size={14} /> AKSA Originals</p><h2 className="mt-5 font-serif text-4xl leading-[.96] tracking-[-.035em] sm:text-5xl">Not just an invitation.<br />A piece of your story.</h2><p className="mt-6 text-sm leading-7 text-white/65">Commission a soundtrack or visual treatment that carries the character of your relationship beyond the day itself.</p></div>
        <div className="mt-12 grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-[1.75rem] border border-white/15 bg-white/[.07] p-5 backdrop-blur sm:p-7"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f4cf6c] text-[#18243a]"><Headphones size={21} /></span><span className="text-[10px] font-bold uppercase tracking-[.18em] text-[#f4cf6c]">Listening room</span></div><h3 className="mt-7 font-serif text-3xl">Original Love Song</h3><p className="mt-3 max-w-md text-sm leading-7 text-white/65">A song direction shaped from your shared memories, tone, and the little details only the two of you know.</p><div className="mt-6 rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/45">Studio listening sample</p><p className="mt-2 text-sm font-semibold">How sound can live inside an AKSA invitation</p><audio className="mt-4 h-10 w-full" controls preload="metadata"><source src="/template-demos/template-005/the-edit-theme.mp3" type="audio/mpeg" />Your browser does not support audio playback.</audio><p className="mt-3 text-xs leading-5 text-white/45">This is an interface sound sample, not a commissioned client song. Every AKSA Original is developed from its own brief.</p></div><a href={whatsappUrl("Hello AKSA, I would like to hear an Original Love Song example and discuss a custom song.")} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#f4cf6c] hover:text-white"><MessageCircle size={16} /> Request a private song sample <ArrowRight size={16} /></a></article>
          <article className="relative overflow-hidden rounded-[1.75rem] border border-white/15 bg-[#dceff3] p-5 text-[#18243a] sm:p-7"><Image src="/brand/aksa-originals-editorial.png" alt="AKSA AI Love Film visual treatment" fill className="object-cover opacity-30 mix-blend-multiply" /><div className="relative"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e96257] text-white"><Film size={21} /></span><span className="rounded-full bg-white/70 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.16em]">Visual treatment</span></div><h3 className="mt-7 font-serif text-3xl">AI Love Film</h3><p className="mt-3 max-w-md text-sm leading-7 text-[#445c69]">An AI-crafted visual journey directed around your relationship, references, music mood, and the world you want guests to enter.</p><div className="mt-6 rounded-2xl border border-[#18243a]/10 bg-white/75 p-5 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#628093]">Preview format</p><p className="mt-2 text-sm leading-6 text-[#415766]">Every film is privately developed. Request a consultation to review the available visual directions and sample treatment.</p><div className="mt-4 flex items-center gap-2 text-xs font-bold text-[#c6534b]"><CirclePlay size={17} /> Private screening available on request</div></div><a href={whatsappUrl("Hello AKSA, I would like to see an AI Love Film example and discuss a visual treatment.")} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#c6534b] hover:text-[#18243a]"><MessageCircle size={16} /> Request an AI film sample <ArrowRight size={16} /></a></div></article></div>
      </div>
    </section>

    <section id="testimonials" className="bg-[#f5efe5] px-5 py-20 sm:px-6 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.74fr_1fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#a8793d]">Client stories</p><h2 className="mt-4 font-serif text-4xl leading-[.96] tracking-[-.035em] sm:text-5xl">Real words deserve<br />real permission.</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#6c6257]">AKSA will publish client feedback only with the client&apos;s approval. That keeps this space honest, personal, and worth reading.</p><a href={whatsappUrl("Hello AKSA, I would like to ask for client work examples and references.")} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#18243a] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#293957]"><MessageCircle size={16} /> Request client references</a></div><div className="rounded-[1.75rem] border border-[#a8793d]/20 bg-[#fffaf5] p-6 shadow-[0_16px_40px_rgba(77,56,33,.08)] sm:p-8"><Quote size={30} className="text-[#c99b45]" /><p className="mt-6 font-serif text-3xl leading-tight text-[#263247]">Your approved story could be the next one featured here.</p><p className="mt-5 max-w-lg text-sm leading-7 text-[#6a707b]">For now, prospective clients can explore the live portfolio above or request relevant examples directly from AKSA. Verified testimonials will be added as each client gives written consent.</p><div className="mt-8 flex items-center gap-3 border-t border-[#18243a]/10 pt-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f4cf6c] text-xs font-bold text-[#18243a]">AK</span><div><p className="text-sm font-bold">Verified stories, not filler.</p><p className="text-xs text-[#7f847f]">AKSA Digital Studio policy</p></div></div></div></div></section>

    <section id="faq" className="bg-[#fffaf5] px-5 py-20 sm:px-6 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.68fr_1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#d95349]">Questions, answered</p><h2 className="mt-4 font-serif text-4xl leading-[.96] tracking-[-.035em] sm:text-5xl">Everything clear<br /><span className="text-[#9aa2ad]">before you begin.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-[#5c677d]">Still deciding? Send AKSA your event details and we will guide you to the right starting point.</p><a href={whatsappUrl("Hello AKSA, I have a question before starting my invitation order.")} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#c6534b] hover:text-[#18243a]"><MessageCircle size={17} /> Ask AKSA on WhatsApp <ArrowRight size={16} /></a></div><div className="divide-y divide-[#18243a]/10 rounded-[1.5rem] border border-[#18243a]/10 bg-white px-5 shadow-sm sm:px-7">{faqs.map(([question, answer], index) => <div key={question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span className="font-serif text-xl text-[#18243a] sm:text-2xl">{question}</span><Plus size={18} className={`shrink-0 text-[#e26257] transition ${openFaq === index ? "rotate-45" : ""}`} /></button><div className={`grid transition-[grid-template-rows] duration-300 ${openFaq === index ? "grid-rows-[1fr]" : "grid-rows-[0fr]"}`}><div className="overflow-hidden"><p className="pb-5 text-sm leading-7 text-[#657087]">{answer}</p></div></div></div>)}</div></div></section>
  </>;
}
