export const template021Demo = {
  id: "demo-template-021",
  is_demo: true,
  slug: "crimson-fortune-demo",
  status: "Published",
  template_id: "template-021",
  theme: "elegant-gold",
  groom_name: "Liang Zhao",
  bride_name: "Mei Lin",
  groom_photo: "/template-demos/template-004/groom.webp",
  bride_photo: "/template-demos/template-004/bride.webp",
  groom_cutout: "/template-demos/template-004/groom.webp",
  bride_cutout: "/template-demos/template-004/bride.webp",
  hero_background: "/template-demos/template-004/hero.webp",
  gallery: "/template-demos/template-004/gallery-1.webp,/template-demos/template-004/gallery-2.webp,/template-demos/template-004/gallery-3.webp,/template-demos/template-004/hero.webp",
  wedding_date: "2027-09-18",
  story1_year: "2021",
  story1_title: "A fortunate meeting",
  story1_description: "A simple introduction became a story full of laughter, care, and the quiet certainty of finding home in one another.",
  story2_year: "2026",
  story2_title: "A promise with our families",
  story2_description: "Surrounded by the people who shaped us, we chose a future grounded in love, respect, and shared joy.",
  story3_year: "2027",
  story3_title: "The red thread",
  story3_description: "We warmly invite you to celebrate the beginning of our next chapter and the blessings that brought us here.",
  akad_date: "18 September 2027",
  akad_time: "15.00 WIB",
  akad_venue: "The Jade Pavilion",
  akad_address: "Jakarta Selatan\nAn intimate ceremony with our closest families.",
  akad_maps: "",
  reception_date: "18 September 2027",
  reception_time: "18.30 WIB",
  reception_venue: "The Crimson Banquet Hall",
  reception_address: "Dinner, tea ceremony, and an evening of joyful celebration.",
  reception_maps: "",
  live_stream_title: "The ceremony, live.",
  live_stream_url: "",
  sections: {
    hero: true,
    countdown: true,
    couple: true,
    story: true,
    event: true,
    live_stream: false,
    gallery: true,
    rsvp: true,
    gift: false,
    music: false,
  },
};
