export const template022Demo = {
  id: "demo-template-022",
  is_demo: true,
  slug: "jade-dynasty-demo",
  status: "Published",
  template_id: "template-022",
  theme: "forest-green",
  groom_name: "Jun Wei",
  bride_name: "Lian Yue",
  groom_photo: "/template-demos/template-004/groom.webp",
  bride_photo: "/template-demos/template-004/bride.webp",
  groom_cutout: "/template-demos/template-004/groom.webp",
  bride_cutout: "/template-demos/template-004/bride.webp",
  hero_background: "/template-demos/template-004/hero.webp",
  gallery: "/template-demos/template-004/gallery-1.webp,/template-demos/template-004/gallery-2.webp,/template-demos/template-004/gallery-3.webp,/template-demos/template-004/hero.webp",
  wedding_date: "2027-10-23",
  story1_year: "2021",
  story1_title: "A quiet beginning",
  story1_description: "One thoughtful conversation grew into a love that felt steady, generous, and unmistakably like home.",
  story2_year: "2026",
  story2_title: "A blessing from home",
  story2_description: "With our families close and our hearts full, we chose the life we hope to build side by side.",
  story3_year: "2027",
  story3_title: "Jade Dynasty",
  story3_description: "We warmly invite you to share an evening of gratitude, ceremony, and a joyful new beginning.",
  akad_date: "23 October 2027",
  akad_time: "15.30 WIB",
  akad_venue: "The Jade Garden",
  akad_address: "Jakarta Selatan\nA peaceful ceremony with our dearest families.",
  akad_maps: "",
  reception_date: "23 October 2027",
  reception_time: "18.30 WIB",
  reception_venue: "The Dynasty Ballroom",
  reception_address: "Tea ceremony, dinner, and a long evening of celebration.",
  reception_maps: "",
  live_stream_title: "The ceremony, live.",
  live_stream_url: "",
  sections: { hero: true, countdown: true, couple: true, story: true, event: true, live_stream: false, gallery: true, rsvp: true, gift: false, music: false },
};
