export const template023Demo = {
  id: "demo-template-023",
  is_demo: true,
  slug: "porcelain-reverie-demo",
  status: "Published",
  template_id: "template-023",
  theme: "royal-blue",
  groom_name: "Arden Wu",
  bride_name: "Yue Han",
  groom_photo: "/template-demos/template-004/groom.webp",
  bride_photo: "/template-demos/template-004/bride.webp",
  groom_cutout: "/template-demos/template-004/groom.webp",
  bride_cutout: "/template-demos/template-004/bride.webp",
  hero_background: "/template-demos/template-004/hero.webp",
  gallery: "/template-demos/template-004/gallery-1.webp,/template-demos/template-004/gallery-2.webp,/template-demos/template-004/gallery-3.webp,/template-demos/template-004/hero.webp",
  wedding_date: "2027-11-13",
  story1_year: "2022",
  story1_title: "A letter in blue",
  story1_description: "One thoughtful hello became a shared language of patience, laughter, and quiet certainty.",
  story2_year: "2026",
  story2_title: "A promise to keep",
  story2_description: "Among the rituals and people we cherish, we chose a future made with care and intention.",
  story3_year: "2027",
  story3_title: "Porcelain Reverie",
  story3_description: "We warmly invite you to join a celebration of family, ceremony, and the beauty of beginning together.",
  akad_date: "13 November 2027",
  akad_time: "15.30 WIB",
  akad_venue: "The Porcelain House",
  akad_address: "Jakarta Selatan\nAn intimate ceremony for the people who mean the most.",
  akad_maps: "",
  reception_date: "13 November 2027",
  reception_time: "18.30 WIB",
  reception_venue: "The Blue Willow Ballroom",
  reception_address: "Tea ceremony, dinner, and an evening of celebration in blue and white.",
  reception_maps: "",
  live_stream_title: "The ceremony, live.",
  live_stream_url: "",
  sections: { hero: true, countdown: true, couple: true, story: true, event: true, live_stream: false, gallery: true, rsvp: true, gift: false, music: false },
};
