export const template024Demo = {
  id: "demo-template-024",
  is_demo: true,
  slug: "satria-nusantara-demo",
  status: "Published",
  template_id: "template-024",
  theme: "royal-blue",
  groom_name: "Arga Pratama",
  bride_name: "Nadira Putri",
  groom_photo: "/template-demos/template-004/groom.webp",
  bride_photo: "/template-demos/template-004/bride.webp",
  groom_cutout: "/template-demos/template-004/groom.webp",
  bride_cutout: "/template-demos/template-004/bride.webp",
  hero_background: "/template-demos/template-004/hero.webp",
  gallery: "/template-demos/template-004/gallery-1.webp,/template-demos/template-004/gallery-2.webp,/template-demos/template-004/gallery-3.webp,/template-demos/template-004/hero.webp",
  wedding_date: "2027-12-11",
  story1_year: "2021",
  story1_title: "A chance encounter",
  story1_description: "A simple introduction became a friendship defined by support, patience, and shared laughter.",
  story2_year: "2026",
  story2_title: "A promise of partnership",
  story2_description: "With the people who know us best by our side, we chose a future built with courage and tenderness.",
  story3_year: "2027",
  story3_title: "Satria Nusantara",
  story3_description: "We warmly invite you to join a formal celebration of family, devotion, and our new beginning.",
  akad_date: "11 December 2027",
  akad_time: "15.30 WIB",
  akad_venue: "The Officers' Garden",
  akad_address: "Jakarta Selatan\nAn intimate afternoon ceremony with our families.",
  akad_maps: "",
  reception_date: "11 December 2027",
  reception_time: "18.30 WIB",
  reception_venue: "The Honour Ballroom",
  reception_address: "Dinner, a formal reception, and an evening of grateful celebration.",
  reception_maps: "",
  live_stream_title: "The ceremony, live.",
  live_stream_url: "",
  sections: { hero: true, countdown: true, couple: true, story: true, event: true, live_stream: false, gallery: true, rsvp: true, gift: false, music: false },
};
