import { editorialMedia } from "@/components/templates/template-005/shared";
import { amalfiMedia } from "@/components/templates/template-006/shared";
import { lisbonMedia } from "@/components/templates/template-007/shared";
import { chateauMedia } from "@/components/templates/template-008/shared";
import { cinemaMedia } from "@/components/templates/template-009/shared";
import { atelierMedia } from "@/components/templates/template-010/shared";
import { underwaterMedia } from "@/components/templates/template-011/shared";

export const template005Demo = {
  id: "demo-template-005",
  is_demo: true,
  slug: "the-edit-demo",
  status: "Published",
  template_id: "template-005",
  theme: "luxury-black",
  groom_name: "Theo Martin",
  bride_name: "Sienna Vale",
  wedding_date: "2026-11-14",
  hero_background: editorialMedia.hero,
  groom_cutout: editorialMedia.groom,
  bride_cutout: editorialMedia.bride,
  gallery: editorialMedia.gallery.join(","),
  music: "/template-demos/template-005/the-edit-theme.mp3",
  story1_year: "2019",
  story1_title: "The first hello",
  story1_description: "A chance conversation became the beginning of a friendship neither of us wanted to end.",
  story2_year: "2023",
  story2_title: "The question",
  story2_description: "On a quiet evening far from the crowd, we chose a lifetime of little adventures together.",
  story3_year: "2026",
  story3_title: "The celebration",
  story3_description: "Now we cannot wait to celebrate the next chapter with the people who mean the most to us.",
  akad_date: "2026-11-14",
  akad_time: "15:30 WIB",
  akad_venue: "The Glasshouse",
  akad_address: "Jalan Cendana No. 18\nJakarta Selatan",
  akad_maps: "",
  reception_date: "2026-11-14",
  reception_time: "18:30 WIB",
  reception_venue: "The Glasshouse",
  reception_address: "Dinner, speeches, and dancing\nuntil late.",
  reception_maps: "",
  live_stream_title: "",
  live_stream_url: "",
  sections: {
    hero: true,
    countdown: true,
    couple: true,
    story: true,
    event: true,
    live_stream: false,
    gallery: true,
    rsvp: true,
    gift: false,
    music: true,
  },
};

export const template006Demo = {
  id: "demo-template-006",
  is_demo: true,
  slug: "amalfi-afterglow-demo",
  status: "Published",
  template_id: "template-006",
  theme: "elegant-gold",
  groom_name: "Matteo Romano",
  bride_name: "Sofia Bellini",
  wedding_date: "2027-06-18",
  hero_background: amalfiMedia.hero,
  groom_cutout: amalfiMedia.groom,
  bride_cutout: amalfiMedia.bride,
  gallery: "",
  story1_year: "2021",
  story1_title: "A chance summer",
  story1_description: "One long walk, one shared espresso, and a conversation neither of us wanted to end.",
  story2_year: "2025",
  story2_title: "The question",
  story2_description: "With the coast glowing behind us, a simple question became our favourite answer.",
  story3_year: "2027",
  story3_title: "Our golden hour",
  story3_description: "Now we are gathering the people we love for a celebration under the Amalfi sky.",
  akad_date: "2027-06-18",
  akad_time: "16:30",
  akad_venue: "Villa Limonaia",
  akad_address: "Amalfi Coast, Italy\nAmong the lemon trees and blue sea.",
  akad_maps: "",
  reception_date: "2027-06-18",
  reception_time: "18:30",
  reception_venue: "Terrazza al Tramonto",
  reception_address: "Dinner, dancing, and a sunset toast by the water.",
  reception_maps: "",
  live_stream_title: "",
  live_stream_url: "",
  sections: { hero: true, countdown: true, couple: true, story: true, event: true, live_stream: false, gallery: true, rsvp: true, gift: false, music: false },
};

export const template007Demo = {
  id: "demo-template-007",
  is_demo: true,
  slug: "lisbon-letters-demo",
  status: "Published",
  template_id: "template-007",
  theme: "royal-blue",
  groom_name: "Leon Duarte",
  bride_name: "Mira Santos",
  wedding_date: "2027-09-25",
  hero_background: lisbonMedia.hero,
  groom_cutout: lisbonMedia.groom,
  bride_cutout: lisbonMedia.bride,
  gallery: "",
  story1_year: "2022",
  story1_title: "The first postcard",
  story1_description: "A handwritten note arrived at exactly the right time, inviting us to see the city and each other differently.",
  story2_year: "2026",
  story2_title: "The promise",
  story2_description: "Between blue tile walls and bright afternoon light, we promised to keep choosing one another.",
  story3_year: "2027",
  story3_title: "The celebration",
  story3_description: "Now we invite our favourite people to add their own beautiful line to our story.",
  akad_date: "2027-09-25",
  akad_time: "15:00",
  akad_venue: "Pátio Azul",
  akad_address: "Lisbon, Portugal\nA courtyard tiled in cobalt blue.",
  akad_maps: "",
  reception_date: "2027-09-25",
  reception_time: "18:00",
  reception_venue: "Miradouro Terrace",
  reception_address: "An evening toast above the city rooftops.",
  reception_maps: "",
  live_stream_title: "",
  live_stream_url: "",
  sections: { hero: true, countdown: true, couple: true, story: true, event: true, live_stream: false, gallery: true, rsvp: true, gift: false, music: false },
};
export const template008Demo = { id:"demo-template-008",is_demo:true,slug:"chateau-de-lune-demo",status:"Published",template_id:"template-008",theme:"elegant-gold",groom_name:"Étienne Laurent",bride_name:"Camille Moreau",wedding_date:"2027-10-16",hero_background:chateauMedia.hero,groom_cutout:chateauMedia.groom,bride_cutout:chateauMedia.bride,gallery:"",story1_year:"2022",story1_title:"A first dance",story1_description:"A quiet beginning became our favourite tradition.",story2_year:"2026",story2_title:"The promise",story2_description:"Under a pale moon, we chose forever.",story3_year:"2027",story3_title:"Château de Lune",story3_description:"Now we gather our dearest people for one luminous evening.",akad_date:"2027-10-16",akad_time:"16:00",akad_venue:"Château de Lune",akad_address:"A formal garden celebration.",reception_date:"2027-10-16",reception_time:"18:30",reception_venue:"The Orangerie",reception_address:"Dinner and dancing by candlelight.",live_stream_title:"The ceremony, live.",live_stream_url:"",sections:{hero:true,countdown:true,couple:true,story:true,event:true,live_stream:true,gallery:true,rsvp:true,gift:false,music:false}};
export const template009Demo = { ...template008Demo, id:"demo-template-009", slug:"midnight-cinema-demo", template_id:"template-009", groom_name:"Julian Reed", bride_name:"Elena Rose", wedding_date:"2027-12-31", hero_background:cinemaMedia.hero, groom_cutout:cinemaMedia.groom, bride_cutout:cinemaMedia.bride, story3_title:"Final frame", live_stream_title:"Premiere live", sections:{...template008Demo.sections,live_stream:true} };
export const template010Demo = { id:"demo-template-010",is_demo:true,slug:"atelier-no-27-demo",status:"Published",template_id:"template-010",theme:"luxury-black",groom_name:"Julien Laurent",bride_name:"Aurelia Moreau",wedding_date:"2026-12-19",hero_background:atelierMedia.hero,groom_cutout:atelierMedia.groom,bride_cutout:atelierMedia.bride,gallery:"",story1_year:"2021",story1_title:"The first fitting",story1_description:"A shared table, a few sketches, and the beginning of a love that fitted perfectly.",story2_year:"2025",story2_title:"The promise",story2_description:"Among handwritten notes and candlelight, we chose a future made for two.",story3_year:"2026",story3_title:"The final collection",story3_description:"This December, we gather the people who have shaped every beautiful detail.",akad_date:"2026-12-19",akad_time:"16:00 WIB",akad_venue:"The Atelier Ballroom",akad_address:"Jakarta Selatan\nAn intimate afternoon ceremony.",akad_maps:"",reception_date:"2026-12-19",reception_time:"19:00 WIB",reception_venue:"No. 27 Private Dining",reception_address:"Candlelit dinner, champagne, and a midnight toast.",reception_maps:"",live_stream_title:"The ceremony, live.",live_stream_url:"",sections:{hero:true,countdown:true,couple:true,story:true,event:true,live_stream:true,gallery:true,rsvp:true,gift:false,music:false}};
export const template011Demo = { id:"demo-template-011",is_demo:true,slug:"underwater-vows-demo",status:"Published",template_id:"template-011",theme:"royal-blue",groom_name:"Kai Pratama",bride_name:"Maya Lestari",wedding_date:"2027-01-17",hero_background:underwaterMedia.hero,groom_cutout:underwaterMedia.groom,bride_cutout:underwaterMedia.bride,gallery:"",story1_year:"2020",story1_title:"A shared horizon",story1_description:"A first trip to the coast became the beginning of a life full of blue skies and brave dreams.",story2_year:"2026",story2_title:"The promise",story2_description:"At the edge of the water, we promised to keep finding our way back to each other.",story3_year:"2027",story3_title:"Underwater Vows",story3_description:"On 17 January, we gather our favourite people for a celebration by the sea.",akad_date:"2027-01-17",akad_time:"15:30 WIB",akad_venue:"The Shoreline Chapel",akad_address:"Nusa Dua, Bali\nA sunset ceremony by the water.",akad_maps:"",reception_date:"2027-01-17",reception_time:"18:30 WIB",reception_venue:"Coral Bay Resort",reception_address:"Dinner, dancing, and a moonlit ocean toast.",reception_maps:"",live_stream_title:"Broadcast from the shore",live_stream_url:"",sections:{hero:true,countdown:true,couple:true,story:true,event:true,live_stream:true,gallery:true,rsvp:true,gift:false,music:false}};
