"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import CopyButton from "@/components/CopyButton";
import Guestbook from "@/components/Guestbook";
import MotionSection from "@/components/motion/MotionSection";
import RSVPForm from "@/components/RSVPForm";
import { defaultSections } from "@/lib/defaultSections";
import { underwaterMedia } from "./shared";

const enabled = (invitation: { sections?: Record<string, unknown> }) => ({ ...defaultSections, ...(invitation.sections ?? {}) });
const first = (value?: string) => value?.trim().split(" ")[0] || "";
const timeLeft = (date?: string) => { const target = new Date(`${date || ""}T00:00:00`).getTime(); const gap = Number.isNaN(target) ? 0 : Math.max(0, target - Date.now()); return [[Math.floor(gap / 86400000), "Days"], [Math.floor(gap / 3600000) % 24, "Hours"], [Math.floor(gap / 60000) % 60, "Minutes"], [Math.floor(gap / 1000) % 60, "Seconds"]]; };

function Cover({ invitation }: TemplateProps) {
  const [opened, setOpened] = useState(false);
  if (opened) return null;
  return <section className="fixed inset-0 z-50 grid place-items-center overflow-hidden bg-[#061b35] p-5 text-white"><div className="absolute inset-0 opacity-55" style={{ backgroundImage: `linear-gradient(rgba(3,14,34,.18),rgba(1,20,44,.74)),url('${invitation.hero_background || underwaterMedia.hero}')`, backgroundSize: "cover", backgroundPosition: "center" }} /><div className="absolute -left-24 top-1/4 h-72 w-72 rounded-full border border-cyan-100/20 bg-cyan-100/10 blur-sm" /><div className="relative w-full max-w-md overflow-hidden rounded-[2rem] border border-cyan-100/45 bg-[#082848]/70 p-3 shadow-2xl backdrop-blur"><div className="border border-cyan-100/25 px-8 py-12 text-center"><p className="text-[10px] font-bold uppercase tracking-[.48em] text-[#94ecf2]">AKSA · Underwater Vows</p><p className="mt-10 text-xs uppercase tracking-[.28em] text-white/70">A tide of forever</p><h1 className="mt-5 font-serif text-6xl leading-[.82]">{first(invitation.groom_name) || "Kai"}<br /><span className="text-[#7ce1e7] italic">&amp;</span> {first(invitation.bride_name) || "Maya"}</h1><div className="mx-auto mt-8 h-px w-20 bg-[#88dbe2]" /><p className="mt-7 text-[10px] font-bold uppercase tracking-[.28em] text-white/75">{invitation.wedding_date}</p><p className="mt-8 font-serif italic text-lg text-[#b7f0ed]">{invitation.guest_name || "Dear Guest"}</p><button onClick={() => { window.dispatchEvent(new Event("invitation-opened")); setOpened(true); }} className="mt-9 rounded-full border border-[#9cebed]/70 bg-white/10 px-7 py-3 text-[10px] font-bold uppercase tracking-[.22em] transition hover:bg-[#9cebed] hover:text-[#06203b]">Dive into the invitation</button></div></div></section>;
}

function Hero({ invitation }: TemplateProps) {
  const show = enabled(invitation); const [clock, setClock] = useState(() => timeLeft(invitation.wedding_date));
  useEffect(() => { const ticker = setInterval(() => setClock(timeLeft(invitation.wedding_date)), 1000); return () => clearInterval(ticker); }, [invitation.wedding_date]);
  if (!show.hero && !show.countdown) return null;
  return <section className="relative z-10 overflow-hidden bg-[#061b35] px-5 py-20 text-white sm:px-8"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "radial-gradient(circle at 15% 18%, #7be7eb 0 2px, transparent 3px), radial-gradient(circle at 80% 75%, #d9ffff 0 1px, transparent 2px)", backgroundSize: "44px 57px, 32px 44px" }} /><div className="absolute -right-24 top-1/4 h-80 w-80 rounded-full bg-cyan-200/25 blur-3xl motion-safe:animate-pulse" /><div className="relative mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.46em] text-[#94ecf2]">Where the sea meets forever</p><h1 className="mt-6 font-serif text-6xl leading-[.8] sm:text-8xl">{first(invitation.groom_name) || "Kai"}<br /><span className="italic text-[#7ce1e7]">&amp;</span> {first(invitation.bride_name) || "Maya"}</h1><p className="mt-9 max-w-md text-base leading-8 text-white/70">Beneath an endless sky and beside a blue horizon, we are beginning our deepest adventure.</p><p className="mt-10 border-l border-[#83e3e4] pl-4 text-[10px] font-bold uppercase tracking-[.25em] text-[#c5f8f5]">Save the date · {invitation.wedding_date}</p></div><div className="relative mx-auto w-full max-w-2xl"><div className="relative aspect-[4/5] overflow-hidden rounded-[3rem] border border-cyan-100/35 shadow-[0_0_65px_rgba(77,225,230,.25)]"><Image src={invitation.hero_background || underwaterMedia.hero} alt="Underwater Vows ocean artwork" fill priority unoptimized className="object-cover" /><div className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-[#04152c]/80 to-transparent" /></div><div className="absolute -bottom-6 -left-3 grid h-20 w-20 place-items-center rounded-full border border-white/45 bg-[#75dce0]/25 text-xs font-bold uppercase tracking-[.18em] backdrop-blur sm:-left-8">Pearl<br />tide</div></div></div>{show.countdown !== false && <div className="relative mx-auto mt-20 grid max-w-5xl grid-cols-2 gap-4 sm:grid-cols-4">{clock.map(([number, label]) => <div key={String(label)} className="relative overflow-hidden rounded-full border border-cyan-100/30 bg-[#0a3457]/70 px-3 py-8 text-center shadow-lg"><span className="absolute left-3 top-3 h-3 w-3 rounded-full border border-white/60" /><p className="font-serif text-4xl text-[#e9ffff]">{String(number).padStart(2, "0")}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.2em] text-[#9debed]">{label}</p></div>)}</div>}</section>;
}

function Couple({ invitation }: TemplateProps) {
  if (!enabled(invitation).couple) return null;
  const people = [["The diver", invitation.groom_name || "Kai Santoso", invitation.groom_cutout || invitation.groom_photo || underwaterMedia.groom], ["The ocean heart", invitation.bride_name || "Maya Pradana", invitation.bride_cutout || invitation.bride_photo || underwaterMedia.bride]];
  return <MotionSection><section className="relative z-10 bg-[#e4fbfa] px-5 py-20 text-[#07233d] sm:px-8"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#18798a]">The couple</p><h2 className="mt-4 font-serif text-5xl">Two currents, one ocean.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2">{people.map(([role, name, image]) => <article key={String(role)} className="overflow-hidden rounded-t-[9rem] border border-[#6dbec3]/45 bg-white p-4 shadow-lg"><div className="relative h-[31rem] overflow-hidden rounded-t-[7.5rem] bg-gradient-to-b from-[#c6f2ef] to-[#eefcfb]"><Image src={String(image)} alt={String(name)} fill unoptimized className="object-contain object-bottom" /></div><p className="mt-6 text-[10px] font-bold uppercase tracking-[.3em] text-[#18798a]">{role}</p><h3 className="mt-2 pb-3 font-serif text-4xl">{name}</h3></article>)}</div></div></section></MotionSection>;
}

function Story({ invitation }: TemplateProps) {
  const chapters = [[invitation.story1_year, invitation.story1_title, invitation.story1_description], [invitation.story2_year, invitation.story2_title, invitation.story2_description], [invitation.story3_year, invitation.story3_title, invitation.story3_description]].filter((item) => item.some(Boolean));
  if (!enabled(invitation).story || !chapters.length) return null;
  return <MotionSection><section className="relative z-10 bg-[#0a3457] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#93e9ea]">Ocean chapters</p><h2 className="mt-4 font-serif text-5xl">A love shaped by tides.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{chapters.map(([year, title, description], index) => <article key={`${year}-${title}`} className="rounded-[2rem] border border-cyan-100/25 bg-[#0f4168] p-7"><span className="grid h-10 w-10 place-items-center rounded-full border border-[#a1f0ee]/45 font-serif text-lg text-[#a1f0ee]">{index + 1}</span><p className="mt-7 text-[10px] font-bold uppercase tracking-[.25em] text-[#8fe5e8]">{year}</p><h3 className="mt-3 font-serif text-3xl">{title}</h3><p className="mt-5 text-sm leading-7 text-white/70">{description}</p></article>)}</div></div></section></MotionSection>;
}

function EventCard({ title, date, time, venue, address, maps }: { title: string; date?: string; time?: string; venue?: string; address?: string; maps?: string }) { return <article className="rounded-[2rem] border border-[#6dbec3]/45 bg-white p-8"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#18798a]">{title}</p><h3 className="mt-6 font-serif text-3xl">{venue || title}</h3><div className="mt-7 border-y border-dashed border-[#6dbec3]/50 py-4 text-sm"><p className="font-bold">{date}</p><p className="mt-2 text-[#4d6979]">{time}</p></div><p className="mt-6 whitespace-pre-line text-sm leading-7 text-[#4d6979]">{address}</p>{maps && <a href={maps} target="_blank" rel="noreferrer" className="mt-7 inline-block border-b border-[#07233d] pb-1 text-[10px] font-bold uppercase tracking-[.18em]">Find us ↗</a>}</article>; }
function Events({ invitation }: TemplateProps) { if (!enabled(invitation).event) return null; return <MotionSection><section className="relative z-10 bg-[#e4fbfa] px-5 py-20 text-[#07233d] sm:px-8"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#18798a]">The shoreline schedule</p><h2 className="mt-4 font-serif text-5xl">Meet us by the water.</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2"><EventCard title="The vows" date={invitation.akad_date} time={invitation.akad_time} venue={invitation.akad_venue} address={invitation.akad_address} maps={invitation.akad_maps} /><EventCard title="The tide turns" date={invitation.reception_date} time={invitation.reception_time} venue={invitation.reception_venue} address={invitation.reception_address} maps={invitation.reception_maps} /></div></div></section></MotionSection>; }

function LiveStream({ invitation }: TemplateProps) { const url = invitation.live_stream_url?.trim(); if (!url && !invitation.is_demo) return null; return <MotionSection><section className="relative z-10 overflow-hidden bg-[#061b35] px-5 py-20 text-white sm:px-8"><div className="absolute inset-0 opacity-15" style={{ backgroundImage: "radial-gradient(circle at 20% 30%, #86f2ec 0 2px, transparent 3px)", backgroundSize: "32px 32px" }} /><div className="relative mx-auto max-w-4xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#93e9ea]">Broadcast from the shore</p><h2 className="mt-4 font-serif text-5xl">{invitation.live_stream_title || "The ceremony, live."}</h2><div className="mt-10 grid aspect-video place-items-center overflow-hidden rounded-[2rem] border border-cyan-100/35 bg-gradient-to-br from-[#0d5473] to-[#06213f] shadow-[0_0_50px_rgba(104,231,233,.2)]"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-white/55 bg-white/10 pl-1 text-xl">▶</span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.28em]">Live shore feed</p>{url && <a href={url} target="_blank" rel="noreferrer" className="mt-5 inline-block border-b border-white pb-1 text-xs font-bold">Open live stream ↗</a>}</div></div></div></section></MotionSection>; }

function Gallery({ invitation }: TemplateProps) { if (!enabled(invitation).gallery) return null; const images = invitation.gallery?.split(",").map((url: string) => url.trim()).filter(Boolean) || []; const positions = ["0% 0%", "100% 0%", "0% 100%", "100% 100%"]; return <MotionSection><section className="relative z-10 bg-[#f8fffe] px-5 py-20 text-[#07233d] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#18798a]">The blue album</p><h2 className="mt-4 font-serif text-5xl">Pearls of our day.</h2><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">{positions.map((position, index) => <div key={position} className={`overflow-hidden rounded-3xl bg-[#bceeed] ${index === 0 ? "col-span-2 aspect-[4/3] md:col-span-2 md:row-span-2 md:aspect-auto" : "aspect-[4/5]"}`} style={images[index] ? undefined : { backgroundImage: `url('${underwaterMedia.gallerySheet}')`, backgroundPosition: position, backgroundSize: "200% 200%" }}>{images[index] && <div className="relative h-full w-full"><Image src={images[index]} alt="Ocean wedding moment" fill unoptimized className="object-cover" /></div>}</div>)}</div></div></section></MotionSection>; }

function RSVP({ invitation, guest }: TemplateProps) { if (!enabled(invitation).rsvp) return null; return <MotionSection><section className="relative z-10 bg-[#0a3457] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#93e9ea]">Your response</p><h2 className="mt-4 font-serif text-5xl">Sail with us.</h2></div>{invitation.is_demo ? <p className="mx-auto mt-12 max-w-xl rounded-2xl border border-cyan-100/30 p-7 text-center text-sm text-white/75">Your live RSVP form will appear here once this invitation is published.</p> : <div className="mt-12 grid gap-10 md:grid-cols-2"><RSVPForm invitationId={invitation.id} guest={guest ?? null} /><Guestbook invitationId={invitation.id} /></div>}</div></section></MotionSection>; }

function Gift({ invitation }: TemplateProps) { if (!enabled(invitation).gift || !invitation.bank_account) return null; return <section className="relative z-10 bg-[#e4fbfa] px-5 py-20 text-[#07233d]"><div className="mx-auto max-w-xl rounded-[2rem] border border-[#6dbec3]/50 bg-white p-10 text-center shadow-lg"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#18798a]">With gratitude</p><h2 className="mt-4 font-serif text-4xl">A pearl of kindness.</h2><p className="mt-7 text-sm leading-7 text-[#4d6979]">Your presence is our greatest treasure. For those who ask, a little love can be sent here.</p><p className="mt-8 font-serif text-2xl">{invitation.bank_name}</p><p className="mt-3 text-lg">{invitation.bank_account}</p><div className="mt-6"><CopyButton text={invitation.bank_account} /></div></div></section>; }
function Footer({ invitation }: TemplateProps) { return <footer className="relative z-10 bg-[#061b35] px-5 py-16 text-center text-white"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#93e9ea]">Underwater Vows</p><h2 className="mt-5 font-serif text-5xl">{first(invitation.groom_name) || "Kai"} <span className="italic text-[#7ce1e7]">&amp;</span> {first(invitation.bride_name) || "Maya"}</h2><p className="mt-8 text-[10px] uppercase tracking-[.32em] text-white/45">AKSA Digital Studio · Made with a little tide magic</p></footer>; }

export const template011: InvitationTemplate = { id: "template-011", name: "Underwater Vows", description: "A deep-sea wedding invitation in navy, aqua, pearl, and soft moving-light details.", Cover, Hero, Couple, Story, Event: Events, LiveStream, Gallery, RSVP, Gift, Footer };
