"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import CopyButton from "@/components/CopyButton";
import Guestbook from "@/components/Guestbook";
import MotionSection from "@/components/motion/MotionSection";
import RSVPForm from "@/components/RSVPForm";
import { defaultSections } from "@/lib/defaultSections";
import { copenhagenMedia } from "./shared";

const state = (invitation: { sections?: Record<string, unknown> }) => ({ ...defaultSections, ...(invitation.sections ?? {}) });
const name = (value?: string) => value?.trim().split(" ")[0] || "";
const mark = (invitation: TemplateProps["invitation"]) => `${name(invitation.groom_name).slice(0, 1) || "N"} · ${name(invitation.bride_name).slice(0, 1) || "F"}`;
const remaining = (date?: string) => {
  const end = new Date(`${date || ""}T00:00:00`).getTime();
  const ms = Number.isNaN(end) ? 0 : Math.max(0, end - Date.now());
  return [[Math.floor(ms / 86400000), "Days"], [Math.floor(ms / 3600000) % 24, "Hours"], [Math.floor(ms / 60000) % 60, "Minutes"], [Math.floor(ms / 1000) % 60, "Seconds"]] as const;
};
function useClock(date?: string) { const [clock, setClock] = useState(() => remaining(date)); useEffect(() => { const timer = window.setInterval(() => setClock(remaining(date)), 1000); return () => window.clearInterval(timer); }, [date]); return clock; }
function Grid({ className = "" }: { className?: string }) { return <div aria-hidden="true" className={`pointer-events-none absolute inset-0 opacity-40 ${className}`} style={{ backgroundImage: "linear-gradient(#8e877d30 1px, transparent 1px), linear-gradient(90deg, #8e877d30 1px, transparent 1px)", backgroundSize: "52px 52px" }} />; }
function Cover({ invitation }: TemplateProps) { const [open, setOpen] = useState(false); if (open) return null; return <section className="fixed inset-0 z-50 grid place-items-center overflow-hidden bg-[#25221e] p-5 text-[#f5f1e9]"><Grid className="opacity-20" /><div className="relative w-full max-w-md border border-[#d7d0c5] bg-[#efebe3] p-3 text-[#292620] shadow-2xl"><div className="grid min-h-[33rem] border border-[#a79e91] p-7"><p className="self-start text-[9px] font-bold uppercase tracking-[.34em]">AKSA · Copenhagen Quiet</p><div className="self-center"><p className="text-[10px] uppercase tracking-[.28em] text-[#766f65]">A modern gathering</p><h1 className="mt-5 font-serif text-6xl leading-[.82]">{name(invitation.groom_name) || "Noah"}<br /><em className="font-normal text-[#8b7a64]">&amp;</em> {name(invitation.bride_name) || "Freja"}</h1></div><div className="self-end border-t border-[#a79e91] pt-5"><div className="flex items-center justify-between text-[9px] font-bold uppercase tracking-[.2em]"><span>{invitation.wedding_date}</span><span>{mark(invitation)}</span></div><button onClick={() => { window.dispatchEvent(new Event("invitation-opened")); setOpen(true); }} className="mt-7 w-full bg-[#45382f] px-6 py-4 text-[10px] font-bold uppercase tracking-[.22em] text-white transition hover:bg-[#6b5949]">Open invitation</button></div></div></div></section>; }
function Hero({ invitation }: TemplateProps) { const sections = state(invitation); const clock = useClock(invitation.wedding_date); if (!sections.hero && !sections.countdown) return null; return <section className="relative z-10 overflow-hidden bg-[#f4f0e8] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div className="order-2 lg:order-1"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#756e64]">Copenhagen · Denmark</p><h1 className="mt-5 max-w-lg font-serif text-6xl leading-[.82] tracking-[-.04em] sm:text-8xl">A quiet beginning, <em className="font-normal text-[#8c765d]">well made.</em></h1><p className="mt-8 max-w-md text-base leading-8 text-[#645d54]">We are gathering the people we love for an afternoon of honest words, warm wood, and a long table.</p><p className="mt-10 border-l border-[#8d8376] pl-4 text-[10px] font-bold uppercase tracking-[.25em]">{invitation.wedding_date} · {invitation.akad_venue || "The Limestone Room"}</p></div><div className="order-1 border border-[#aca397] bg-[#e8e2d8] p-3 lg:order-2"><div className="relative aspect-[4/5] overflow-hidden"><Image src={invitation.hero_background || copenhagenMedia.hero} alt="Danish modern wedding interior" fill priority unoptimized className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#2a2621]/45 to-transparent" /><p className="absolute bottom-5 left-5 text-[10px] font-bold uppercase tracking-[.28em] text-white">017 / Copenhagen Quiet</p></div></div></div>{sections.countdown !== false && <div className="relative mx-auto mt-16 grid max-w-6xl grid-cols-2 border-l border-t border-[#a79e91] sm:grid-cols-4">{clock.map(([value, label]) => <div key={label} className="border-b border-r border-[#a79e91] bg-[#f8f6f1]/70 p-5 text-center"><p className="font-serif text-4xl">{String(value).padStart(2, "0")}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.18em] text-[#756e64]">{label}</p></div>)}</div>}</section>; }
function Couple({ invitation }: TemplateProps) { if (!state(invitation).couple) return null; const portrait = invitation.groom_photo || invitation.bride_photo || copenhagenMedia.couple; return <MotionSection><section className="relative z-10 bg-[#d9d8d1] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div className="relative aspect-[4/5] overflow-hidden border-[12px] border-[#f4f0e8] shadow-xl"><Image src={portrait} alt="The couple" fill unoptimized className="object-cover" /></div><div><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#756e64]">The people behind the plan</p><h2 className="mt-5 font-serif text-6xl leading-[.86]">{invitation.groom_name || "Noah Lind"}<br /><span className="text-[#8c765d]">&amp;</span> {invitation.bride_name || "Freja Dahl"}</h2><p className="mt-8 max-w-md leading-8 text-[#5e5950]">Two creative minds, one shared appetite for beautiful spaces, good food, and a life with room to breathe.</p><p className="mt-10 border-t border-[#a79e91] pt-4 text-[10px] font-bold uppercase tracking-[.24em]">A calm afternoon. A very good reason to celebrate.</p></div></div></section></MotionSection>; }
function Story({ invitation }: TemplateProps) { const stories = [[invitation.story1_year, invitation.story1_title, invitation.story1_description], [invitation.story2_year, invitation.story2_title, invitation.story2_description], [invitation.story3_year, invitation.story3_title, invitation.story3_description]].filter((item) => item.some(Boolean)); if (!state(invitation).story || !stories.length) return null; return <MotionSection><section className="relative z-10 bg-[#f4f0e8] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#756e64]">Notes from us</p><h2 className="mt-5 font-serif text-5xl">Three small things.</h2><div className="mt-12 grid border-l border-t border-[#a79e91] md:grid-cols-3">{stories.map(([year, title, description], index) => <article key={`${year}-${title}`} className="min-h-64 border-b border-r border-[#a79e91] bg-[#f8f6f1]/80 p-7"><p className="text-[10px] font-bold tracking-[.2em] text-[#8c765d]">0{index + 1} · {year}</p><h3 className="mt-12 font-serif text-3xl">{title}</h3><p className="mt-5 text-sm leading-7 text-[#625c53]">{description}</p></article>)}</div></div></section></MotionSection>; }
function Events({ invitation }: TemplateProps) { if (!state(invitation).event) return null; const card = (heading: string, date?: string, time?: string, venue?: string, address?: string, maps?: string) => <article className="border border-[#a79e91] bg-[#ebe7df] p-7"><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#756e64]">{heading}</p><h3 className="mt-12 font-serif text-3xl">{venue || heading}</h3><div className="mt-8 border-y border-[#a79e91] py-4 text-sm"><p>{date}</p><p className="mt-2 text-[#625c53]">{time}</p></div><p className="mt-6 whitespace-pre-line text-sm leading-7 text-[#625c53]">{address}</p>{maps && <a href={maps} target="_blank" rel="noreferrer" className="mt-7 inline-block border-b border-[#292620] pb-1 text-[10px] font-bold uppercase tracking-[.16em]">Open map ↗</a>}</article>; return <MotionSection><section className="relative z-10 bg-[#d9d8d1] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto max-w-5xl"><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#756e64]">The schedule</p><h2 className="mt-5 font-serif text-5xl">The day, simply.</h2><div className="mt-12 grid gap-5 md:grid-cols-2">{card("The ceremony", invitation.akad_date, invitation.akad_time, invitation.akad_venue, invitation.akad_address, invitation.akad_maps)}{card("The dinner", invitation.reception_date, invitation.reception_time, invitation.reception_venue, invitation.reception_address, invitation.reception_maps)}</div></div></section></MotionSection>; }
function LiveStream({ invitation }: TemplateProps) { const url = invitation.live_stream_url?.trim(); if (!url && !invitation.is_demo) return null; return <MotionSection><section className="relative z-10 bg-[#3e352d] px-5 py-20 text-[#f5f1e9] sm:px-8"><Grid className="opacity-15" /><div className="relative mx-auto max-w-4xl border border-[#9f978d] p-4"><div className="grid aspect-video place-items-center border border-[#9f978d] text-center"><div><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#d8d0c3]">Live from the room</p><span className="mx-auto mt-7 grid h-16 w-16 place-items-center rounded-full border border-[#d8d0c3] pl-1">▶</span><h2 className="mt-6 font-serif text-4xl">{invitation.live_stream_title || "Join us, wherever you are."}</h2>{url && <a href={url} target="_blank" rel="noreferrer" className="mt-5 inline-block border-b border-white pb-1 text-xs">Watch the livestream ↗</a>}</div></div></div></section></MotionSection>; }
function Gallery({ invitation }: TemplateProps) { if (!state(invitation).gallery) return null; const uploaded = invitation.gallery?.split(",").map((image: string) => image.trim()).filter(Boolean) || []; const photos = uploaded.length ? uploaded : [copenhagenMedia.couple, copenhagenMedia.table, copenhagenMedia.hands, invitation.hero_background || copenhagenMedia.hero]; return <MotionSection><section className="relative z-10 bg-[#f4f0e8] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#756e64]">A few good frames</p><h2 className="mt-5 font-serif text-5xl">The details we keep.</h2><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">{photos.slice(0, 4).map((photo: string, index: number) => <div key={`${photo}-${index}`} className={`relative overflow-hidden border border-[#a79e91] bg-[#e8e2d8] ${index === 0 ? "col-span-2 aspect-[4/3]" : "aspect-[4/5]"}`}><Image src={photo} alt="Copenhagen wedding moment" fill unoptimized className="object-cover transition duration-700 hover:scale-105" /></div>)}</div></div></section></MotionSection>; }
function RSVP({ invitation, guest }: TemplateProps) { if (!state(invitation).rsvp) return null; return <MotionSection><section className="relative z-10 bg-[#d9d8d1] px-5 py-20 text-[#292620] sm:px-8"><Grid /><div className="relative mx-auto max-w-4xl"><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#756e64]">Please reply</p><h2 className="mt-5 font-serif text-5xl">Save us a chair.</h2>{invitation.is_demo ? <p className="mt-10 border border-dashed border-[#a79e91] bg-[#f4f0e8]/70 p-7 text-sm leading-7 text-[#625c53]">Your personal RSVP confirmation will appear here once this invitation is published.</p> : <div className="mt-12 grid gap-10 md:grid-cols-2"><RSVPForm invitationId={invitation.id} guest={guest ?? null} /><Guestbook invitationId={invitation.id} /></div>}</div></section></MotionSection>; }
function Gift({ invitation }: TemplateProps) { if (!state(invitation).gift || !invitation.bank_account) return null; return <section className="relative z-10 bg-[#3e352d] px-5 py-20 text-[#f5f1e9]"><div className="mx-auto max-w-xl border border-[#9f978d] p-10 text-center"><p className="text-[10px] font-bold uppercase tracking-[.32em] text-[#d8d0c3]">With appreciation</p><h2 className="mt-5 font-serif text-4xl">A thoughtful gesture.</h2><p className="mt-9 font-serif text-2xl">{invitation.bank_name}</p><p className="mt-3 text-lg">{invitation.bank_account}</p><div className="mt-6"><CopyButton text={invitation.bank_account} /></div></div></section>; }
function Footer({ invitation }: TemplateProps) { return <footer className="relative z-10 bg-[#25221e] px-5 py-16 text-center text-[#f5f1e9]"><Grid className="opacity-15" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.34em] text-[#d8d0c3]">Copenhagen Quiet · AKSA Digital Studio</p><h2 className="mt-5 font-serif text-5xl">{name(invitation.groom_name) || "Noah"} <span className="text-[#b9a488]">&amp;</span> {name(invitation.bride_name) || "Freja"}</h2></div></footer>; }
export const template017: InvitationTemplate = { id: "template-017", name: "Copenhagen Quiet", description: "A Danish-modern invitation of pale stone, walnut, editorial grids, and quiet hotel warmth.", Cover, Hero, Couple, Story, Event: Events, LiveStream, Gallery, RSVP, Gift, Footer };
