import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, Film, HeartHandshake, MessageCircle, Music2, Sparkles } from "lucide-react";
import AksaBrand from "@/components/AksaBrand";

const editions = [
  { code: "digital-invitation", name: "Digital Invitation", eyebrow: "The essential edition", description: "A considered invitation experience, designed to hold every meaningful detail in one beautiful link.", price: "Rp199.000", originalPrice: "Rp250.000", priceNote: "Launch price", icon: Sparkles, color: "#ed6c62", background: "#fdebe7", items: ["Your choice of live invitation template", "Photos, story, schedule, location, RSVP, and gallery", "Personal guest links and RSVP dashboard", "Music, gift registry, and livestream-ready sections"] },
  { code: "original-love-song", name: "Original Love Song", eyebrow: "The signature edition", description: "Your story becomes an original song—made for the invitation, then kept as a memory long after the day.", price: "Rp499.000", priceNote: "Original song concept included", icon: Music2, color: "#f4d078", background: "#19243a", dark: true, featured: true, items: ["Everything in Digital Invitation", "A creative Love Story Brief for the couple", "Original lyric and song concept based on your story", "A soundtrack embedded in your invitation", "One refined review cycle before release"] },
  { code: "ai-love-film", name: "AI Love Film", eyebrow: "The cinematic edition", description: "A short visual love film shaped around your personality, photos, and chosen world—from dreamy to editorial.", price: "From Rp1.499.000", priceNote: "Scope and final treatment are negotiable", icon: Film, color: "#5c7d9f", background: "#e8f0f4", items: ["Everything in Original Love Song", "Creative direction for your AI Love Film", "A cinematic video built around your character and story", "Video premiere embedded in the invitation", "Guided review and final delivery"] },
];
const process = [["01", "Start your brief", "Tell us the date, occasion, style, and the feeling you want to create."], ["02", "Speak with AKSA", "We review the brief personally, confirm the package, and shape the direction together."], ["03", "Confirm & create", "Once the details are agreed, we send payment and production information before work begins."]];

export default function PricingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#fffaf5] text-[#19243a]"><header className="sticky top-0 z-40 border-b border-[#19243a]/10 bg-[#fffaf5]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3.5 sm:px-6 lg:px-10"><Link href="/" aria-label="AKSA Digital Studio home"><AksaBrand /></Link><nav className="hidden items-center gap-7 text-sm font-semibold text-[#5c677d] md:flex"><Link href="/templates">Templates</Link><Link href="/pricing" className="text-[#19243a]">Packages</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-full px-4 py-2 text-sm font-semibold sm:block">Log in</Link><Link href="/order" className="inline-flex items-center gap-2 rounded-full bg-[#ef655a] px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-[#ef655a]/20"><MessageCircle size={16} /> Start your brief</Link></div></div></header>
    <section className="relative isolate px-5 pb-20 pt-16 sm:px-6 lg:px-10 lg:pb-28 lg:pt-24"><div className="pointer-events-none absolute -left-28 top-16 -z-10 h-80 w-80 rounded-full bg-[#f4c979]/30 blur-3xl" /><div className="pointer-events-none absolute right-0 top-1/3 -z-10 h-80 w-80 rounded-full bg-[#bde1ec]/35 blur-3xl" /><div className="mx-auto max-w-5xl text-center"><p className="inline-flex items-center gap-2 rounded-full bg-[#fdebe7] px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#d95a50]"><HeartHandshake size={14}/> Made around your story</p><h1 className="mx-auto mt-7 max-w-4xl font-serif text-5xl leading-[.92] tracking-[-.045em] sm:text-6xl lg:text-7xl">Choose the experience.<br/><span className="text-[#e26257]">We will shape the rest together.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-[#657087] sm:text-lg">Every order begins with a short creative brief, then a direct WhatsApp conversation with AKSA. No payment is requested until the scope is clear.</p><Link href="/order" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#19243a] px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-[#19243a]/20 transition hover:-translate-y-0.5">Start a creative brief <ArrowRight size={17}/></Link></div></section>
    <section className="px-5 pb-20 sm:px-6 lg:px-10 lg:pb-28"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3">{editions.map(({code,name,eyebrow,description,price,originalPrice,priceNote,icon:Icon,color,background,items,dark,featured})=><article key={name} className={`relative flex min-h-[40rem] flex-col overflow-hidden rounded-[2rem] border border-[#19243a]/10 p-7 shadow-xl shadow-[#19243a]/5 sm:p-9 ${dark?"text-white":"text-[#19243a]"}`} style={{background}}>{featured&&<span className="absolute right-6 top-6 rounded-full bg-[#f4d078] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-[#19243a]">AKSA Signature</span>}<span className="grid h-12 w-12 place-items-center rounded-2xl" style={{background:dark?"rgba(255,255,255,.12)":`${color}20`,color}}><Icon size={23}/></span><p className={`mt-8 text-[10px] font-bold uppercase tracking-[.28em] ${dark?"text-[#f4d078]":""}`} style={dark?undefined:{color}}>{eyebrow}</p><h2 className="mt-3 font-serif text-4xl leading-none">{name}</h2><p className={`mt-5 text-sm leading-7 ${dark?"text-white/70":"text-[#657087]"}`}>{description}</p><div className="mt-7 border-t border-current/15 pt-6">{originalPrice&&<p className={`text-sm line-through ${dark?"text-white/50":"text-[#657087]"}`}>{originalPrice}</p>}<p className="mt-1 font-serif text-4xl leading-none">{price}</p><p className={`mt-2 text-xs leading-5 ${dark?"text-white/60":"text-[#657087]"}`}>{priceNote}</p></div><ul className="mt-7 space-y-4 border-t border-current/15 pt-7 text-sm leading-6">{items.map(item=><li key={item} className="flex gap-3"><Check size={17} className="mt-0.5 shrink-0" style={{color}}/>{item}</li>)}</ul><Link href={`/order?package=${code}`} className={`mt-auto inline-flex items-center justify-between border-t border-current/15 pt-7 text-sm font-bold ${dark?"hover:text-[#f4d078]":"hover:text-[#e26257]"}`}>Start this brief <ArrowRight size={17}/></Link></article>)}</div><p className="mx-auto mt-7 max-w-3xl text-center text-sm leading-6 text-[#657087]">After your brief, AKSA confirms the creative direction, delivery window, and any custom additions on WhatsApp before requesting payment.</p></section>
    <section className="bg-[#19243a] px-5 py-20 text-white sm:px-6 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#f4c979]">A clearer way to order</p><h2 className="mt-5 max-w-lg font-serif text-4xl leading-[.98] sm:text-5xl">No guessing. No payment before the conversation.</h2></div><div className="grid gap-6 sm:grid-cols-3">{process.map(([number,title,description])=><article key={number} className="border-t border-white/20 pt-5"><span className="font-serif text-3xl text-[#f4c979]">{number}</span><h3 className="mt-5 text-base font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{description}</p></article>)}</div></div></section>
    <section className="bg-[#e9f3f5] px-5 py-20 sm:px-6 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#4b7d93]">Beyond the invitation</p><h2 className="mt-5 max-w-xl font-serif text-4xl leading-[.98] sm:text-5xl">A soundtrack and a film that belong only to you.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-[#526a78]">Original Love Song and AI Love Film commissions start with the same brief. The more you share, the more personal the creative direction can become.</p><Link href="/order?package=original-love-song" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#19243a] px-5 py-3.5 text-sm font-bold text-white">Start your story brief <ArrowRight size={16}/></Link></div><div className="relative mx-auto w-full max-w-sm overflow-hidden rounded-[2rem] border-[9px] border-[#fffaf5] shadow-2xl"><div className="relative aspect-[4/5]"><Image src="/brand/aksa-originals-editorial.png" alt="AKSA original creative direction" fill unoptimized className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#19243a]/60 to-transparent" /><p className="absolute bottom-5 left-5 text-[10px] font-bold uppercase tracking-[.22em] text-[#f4cf6c]">AKSA Originals</p></div></div></div></section>
    <footer className="bg-[#18243a] px-5 py-8 text-white/65 sm:px-6 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm sm:flex-row"><p>© 2026 AKSA Digital Studio</p><div className="flex gap-5"><Link href="/templates" className="hover:text-white">Templates</Link><Link href="/order" className="hover:text-white">Start a brief</Link><Link href="/login" className="hover:text-white">Log in</Link></div></div></footer>
  </main>;
}
