import Link from "next/link";
import { ArrowRight, Check, Disc3, Film, HeartHandshake, Music2, PlayCircle, Sparkles, Stars } from "lucide-react";

const editions = [
  { name: "Digital Invitation", eyebrow: "The essential edition", description: "A considered invitation experience, designed to hold every meaningful detail in one beautiful link.", icon: Sparkles, color: "#ed6c62", background: "#fdebe7", items: ["Your choice of live invitation template", "Photos, story, schedule, location, RSVP, and gallery", "Personal guest links and RSVP dashboard", "Music, gift registry, and livestream-ready sections"] },
  { name: "Original Love Song", eyebrow: "The signature edition", description: "Your story becomes an original song—made for the invitation, then kept as a memory long after the day.", icon: Music2, color: "#f4d078", background: "#19243a", dark: true, featured: true, items: ["Everything in Digital Invitation", "A creative Love Story Brief for the couple", "Original lyric and song concept based on your story", "A soundtrack embedded in your invitation", "One refined review cycle before release"] },
  { name: "AI Love Film", eyebrow: "The cinematic edition", description: "A short visual love film shaped around your personality, photos, and chosen world—from dreamy to editorial.", icon: Film, color: "#5c7d9f", background: "#e8f0f4", items: ["Everything in Original Love Song", "Creative direction for your AI Love Film", "A cinematic video built around your character and story", "Video premiere embedded in the invitation", "Guided review and final delivery"] },
];
const process = [["01", "Tell us your story", "Share your relationship, favourite memories, visual references, and the feeling you want guests to carry."], ["02", "Shape the experience", "Choose an invitation, soundtrack direction, and—if you choose it—a cinematic world for your film."], ["03", "Approve your release", "Review the creative direction, refine the details, then publish one beautiful home for the celebration."]];

export default function PricingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#fcfaf7] text-[#19243a]">
    <header className="border-b border-[#19243a]/10 bg-[#fcfaf7]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#19243a] font-serif text-lg font-bold text-[#f4c979]">A</span><span className="font-serif text-xl font-semibold tracking-tight">AKSA</span></Link><nav className="hidden items-center gap-8 text-sm font-medium text-[#657087] md:flex"><Link href="/templates">Templates</Link><Link href="/pricing" className="text-[#19243a]">Experiences</Link></nav><div className="flex items-center gap-2 sm:gap-3"><Link href="/login" className="rounded-full px-3 py-2.5 text-sm font-semibold sm:px-5">Log in</Link><Link href="/signup" className="inline-flex items-center gap-2 rounded-full bg-[#ed6c62] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#ed6c62]/20 sm:px-5">Start your story <ArrowRight size={15}/></Link></div></div></header>
    <section className="relative isolate px-6 pb-24 pt-20 lg:px-10 lg:pb-32 lg:pt-28"><div className="pointer-events-none absolute -left-28 top-16 -z-10 h-80 w-80 rounded-full bg-[#f4c979]/20 blur-3xl"/><div className="pointer-events-none absolute right-0 top-1/3 -z-10 h-80 w-80 rounded-full bg-[#f4b7aa]/25 blur-3xl"/><div className="mx-auto max-w-7xl text-center"><p className="inline-flex items-center gap-2 rounded-full bg-[#fdebe7] px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#d95a50]"><HeartHandshake size={14}/> Made around your story</p><h1 className="mx-auto mt-7 max-w-4xl font-serif text-5xl leading-[.92] tracking-[-.045em] sm:text-6xl lg:text-8xl">Not just an invitation.<br/><span className="text-[#e26257]">Your love, in its own form.</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-[#657087] sm:text-xl">Start with a beautiful digital invitation, then turn the details that make you two unique into a song or a film made only for your day.</p><Link href="/signup" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#19243a] px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-[#19243a]/20">Begin your story <ArrowRight size={17}/></Link></div></section>
    <section className="px-6 pb-24 lg:px-10 lg:pb-32"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3">{editions.map(({name,eyebrow,description,icon:Icon,color,background,items,dark,featured})=><article key={name} className={`relative flex min-h-[39rem] flex-col overflow-hidden rounded-[2rem] p-7 shadow-xl shadow-[#19243a]/5 sm:p-9 ${dark?"text-white":"text-[#19243a]"}`} style={{background}}>{featured&&<span className="absolute right-6 top-6 rounded-full bg-[#f4d078] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-[#19243a]">AKSA Signature</span>}<span className="grid h-12 w-12 place-items-center rounded-2xl" style={{background:dark?"rgba(255,255,255,.12)":`${color}20`,color}}><Icon size={23}/></span><p className={`mt-8 text-[10px] font-bold uppercase tracking-[.28em] ${dark?"text-[#f4d078]":""}`} style={dark?undefined:{color}}>{eyebrow}</p><h2 className="mt-3 font-serif text-4xl leading-none">{name}</h2><p className={`mt-5 text-sm leading-7 ${dark?"text-white/70":"text-[#657087]"}`}>{description}</p><ul className="mt-8 space-y-4 border-t border-current/15 pt-7 text-sm leading-6">{items.map(item=><li key={item} className="flex gap-3"><Check size={17} className="mt-0.5 shrink-0" style={{color}}/>{item}</li>)}</ul><Link href="/signup" className={`mt-auto inline-flex items-center justify-between border-t border-current/15 pt-7 text-sm font-bold ${dark?"hover:text-[#f4d078]":"hover:text-[#e26257]"}`}>Create this experience <ArrowRight size={17}/></Link></article>)}</div><p className="mx-auto mt-7 max-w-3xl text-center text-sm leading-6 text-[#657087]">Every creative edition starts with a personal brief. Final scope, delivery window, and investment are confirmed before production begins.</p></section>
    <section className="bg-[#19243a] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#f4c979]">How it unfolds</p><h2 className="mt-5 max-w-lg font-serif text-5xl leading-[1.02] tracking-[-.035em] sm:text-6xl">A creative process that still feels simple.</h2><p className="mt-6 max-w-md text-base leading-7 text-white/60">We give the meaningful pieces room to breathe, while keeping the steps clear from first story to final share.</p></div><div className="grid gap-8 sm:grid-cols-3">{process.map(([number,title,description])=><article key={number} className="border-t border-white/20 pt-5"><span className="font-serif text-3xl text-[#f4c979]">{number}</span><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{description}</p></article>)}</div></div></section>
    <section className="bg-[#f6e3d8] px-6 py-24 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-[#b94f49]"><Disc3 size={15}/> Your song. Your scene. Your day.</p><h2 className="mt-5 font-serif text-5xl leading-[1.02] tracking-[-.04em] text-[#19243a] sm:text-6xl">A soundtrack and a film that belong only to you.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#657087]">AKSA creates original material from the details you choose to share. We do not imitate a musician’s voice or create a likeness without the couple’s permission.</p><Link href="/signup" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#19243a] px-6 py-3.5 text-sm font-bold text-white">Start your Love Story Brief <ArrowRight size={17}/></Link></div><div className="relative mx-auto grid aspect-square w-full max-w-sm place-items-center rounded-full border-[22px] border-[#19243a] bg-[#f4c979] shadow-2xl"><div className="grid h-40 w-40 place-items-center rounded-full border-8 border-[#f6e3d8] bg-[#ed6c62] text-center text-[#19243a]"><PlayCircle size={36}/><span className="mt-2 text-[9px] font-bold uppercase tracking-[.2em]">AKSA original</span></div><Stars className="absolute -right-5 top-10 text-[#ed6c62]" size={38}/></div></div></section>
    <footer className="border-t border-[#19243a]/10 bg-[#fcfaf7] px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-sm text-[#657087] sm:flex-row"><p>© 2026 AKSA Digital Studio</p><div className="flex gap-5"><Link href="/templates">Templates</Link><Link href="/login">Log in</Link><Link href="/signup">Create an invitation</Link></div></div></footer>
  </main>;
}
