"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import type { InvitationTemplate, TemplateProps } from "../types";
import CopyButton from "@/components/CopyButton";
import Guestbook from "@/components/Guestbook";
import MotionSection from "@/components/motion/MotionSection";
import RSVPForm from "@/components/RSVPForm";
import { defaultSections } from "@/lib/defaultSections";
import { cinemaMedia as chateauMedia } from "./shared";
const S=(i:{sections?:Record<string,unknown>})=>({...defaultSections,...(i.sections??{})}); const N=(v?:string)=>v?.trim().split(" ")[0]||"";
const C=(d?:string)=>{const t=new Date(`${d||""}T00:00:00`).getTime(),r=Number.isNaN(t)?0:Math.max(0,t-Date.now());return [[Math.floor(r/864e5),"Days"],[Math.floor(r/36e5)%24,"Hours"],[Math.floor(r/6e4)%60,"Minutes"],[Math.floor(r/1e3)%60,"Seconds"]]};
const Rule=()=> <div className="h-px bg-gradient-to-r from-transparent via-[#8fa0b5] to-transparent"/>;
function Cover({invitation}:TemplateProps){const[o,setO]=useState(false);if(o)return null;const g=N(invitation.groom_name)||"Étienne",b=N(invitation.bride_name)||"Camille";return <section className="fixed inset-0 z-50 grid place-items-center overflow-hidden bg-[#e9e5dc] p-5" style={{backgroundImage:`linear-gradient(rgba(20,34,54,.28),rgba(20,34,54,.6)),url('${invitation.hero_background||chateauMedia.hero}')`,backgroundSize:"cover",backgroundPosition:"center"}}><div className="w-full max-w-md border border-[#e9e5dc]/70 bg-[#fbfaf6]/95 p-2 text-center shadow-2xl"><div className="border border-[#8fa0b5]/70 px-8 py-10 text-[#1c2b42]"><p className="text-[10px] font-bold uppercase tracking-[.45em] text-[#70869d]">AKSA · Château de Lune</p><p className="mt-8 font-serif italic">The honour of your presence is requested</p><h1 className="mt-4 font-serif text-6xl leading-[.85]">{g}<br/><span className="text-[#8fa0b5]">&amp;</span> {b}</h1><Rule/><p className="my-7 text-[10px] font-bold uppercase tracking-[.28em]">{invitation.wedding_date}</p><p className="font-serif text-xl">{invitation.guest_name||"Dear Guest"}</p><button onClick={()=>{window.dispatchEvent(new Event("invitation-opened"));setO(true)}} className="mt-9 border border-[#1c2b42] px-7 py-3 text-xs font-bold tracking-[.2em] transition hover:bg-[#1c2b42] hover:text-white">OPEN INVITATION</button></div></div></section>}
function Hero({invitation}:TemplateProps){const s=S(invitation),[c,setC]=useState(()=>C(invitation.wedding_date));useEffect(()=>{const x=setInterval(()=>setC(C(invitation.wedding_date)),1000);return()=>clearInterval(x)},[invitation.wedding_date]);if(!s.hero&&!s.countdown)return null;return <section className="relative z-10 bg-[#fbfaf6] px-5 py-20 text-[#1c2b42] sm:px-8"><div className="mx-auto max-w-6xl overflow-hidden border border-[#8fa0b5]/45 bg-[#e9e5dc] shadow-xl md:grid md:grid-cols-2"><div className="relative min-h-[34rem]"><Image src={invitation.hero_background||chateauMedia.hero} alt="Château de Lune" fill priority unoptimized className="object-cover"/></div><div className="flex flex-col justify-center p-9 md:p-14"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">A moonlit celebration</p><h1 className="mt-6 font-serif text-6xl leading-[.84]">{N(invitation.groom_name)||"Étienne"}<br/><span className="text-[#8fa0b5]">&amp;</span> {N(invitation.bride_name)||"Camille"}</h1><p className="mt-7 text-sm leading-7 text-[#1c2b42]/70">An evening of garden roses, candlelight, and timeless promises.</p><p className="mt-8 text-xs font-bold tracking-[.18em]">{invitation.wedding_date}</p></div></div>{s.countdown!==false&&<div className="mx-auto mt-12 grid max-w-5xl grid-cols-4 border border-[#8fa0b5]/35 bg-white py-6 text-center">{c.map(([v,l],i)=><div key={String(l)} className={i?"border-l border-[#8fa0b5]/35":""}><p className="font-serif text-4xl">{String(v).padStart(2,"0")}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.18em] text-[#70869d]">{l}</p></div>)}</div>}</section>}
function Couple({invitation}:TemplateProps){if(!S(invitation).couple)return null;const p=[['The groom',invitation.groom_name||'Étienne Laurent',invitation.groom_cutout||invitation.groom_photo||chateauMedia.groom],['The bride',invitation.bride_name||'Camille Moreau',invitation.bride_cutout||invitation.bride_photo||chateauMedia.bride]];return <MotionSection><section className="relative z-10 bg-[#1c2b42] px-5 py-20 text-[#fbfaf6] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.42em] text-[#a9b8c8]">The couple</p><h2 className="mt-4 text-center font-serif text-5xl">A house of two.</h2><div className="mt-14 grid gap-6 md:grid-cols-2">{p.map(([r,n,img])=><article key={String(r)} className="bg-[#fbfaf6] p-4 text-[#1c2b42]"><div className="relative h-[30rem] bg-[#dfe4e8]"><Image src={String(img)} alt={String(n)} fill unoptimized className="object-contain object-bottom"/></div><p className="mt-6 text-[9px] font-bold uppercase tracking-[.32em] text-[#70869d]">{r}</p><h3 className="mt-2 font-serif text-4xl">{n}</h3></article>)}</div></div></section></MotionSection>}
function Story({invitation}:TemplateProps){const a=[[invitation.story1_year,invitation.story1_title,invitation.story1_description],[invitation.story2_year,invitation.story2_title,invitation.story2_description],[invitation.story3_year,invitation.story3_title,invitation.story3_description]].filter(x=>x[0]||x[1]||x[2]);if(!S(invitation).story||!a.length)return null;return <MotionSection><section className="relative z-10 bg-[#e9e5dc] px-5 py-20 text-[#1c2b42] sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">Our history</p><h2 className="mt-4 text-center font-serif text-5xl">Pages from our story.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{a.map(([y,t,d])=><article key={String(y)} className="border border-[#8fa0b5]/35 bg-[#fbfaf6] p-7"><p className="font-serif text-3xl text-[#8fa0b5]">{y}</p><h3 className="mt-4 font-serif text-2xl">{t}</h3><p className="mt-4 text-sm leading-7 text-[#1c2b42]/70">{d}</p></article>)}</div></div></section></MotionSection>}
function EventCard({title,date,time,venue,address,maps}:{title:string,date?:string,time?:string,venue?:string,address?:string,maps?:string}){return <article className="border border-[#8fa0b5]/35 bg-[#fbfaf6] p-8"><p className="text-[9px] font-bold uppercase tracking-[.32em] text-[#70869d]">{title}</p><h3 className="mt-6 font-serif text-3xl">{venue||title}</h3><p className="mt-6 text-sm font-bold">{date}</p><p className="mt-2 text-sm text-[#1c2b42]/70">{time}</p><p className="mt-5 whitespace-pre-line text-sm leading-7 text-[#1c2b42]/70">{address}</p>{maps&&<a href={maps} target="_blank" className="mt-6 inline-block border border-[#1c2b42] px-4 py-3 text-[10px] font-bold tracking-[.15em]">VIEW LOCATION ↗</a>}</article>}
function Celebration({invitation}:TemplateProps){if(!S(invitation).event)return null;return <MotionSection><section className="relative z-10 bg-[#fbfaf6] px-5 py-20 text-[#1c2b42] sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">The day</p><h2 className="mt-4 text-center font-serif text-5xl">Join us at the château.</h2><div className="mt-14 grid gap-6 md:grid-cols-2"><EventCard title="Ceremony" date={invitation.akad_date} time={invitation.akad_time} venue={invitation.akad_venue} address={invitation.akad_address} maps={invitation.akad_maps}/><EventCard title="Reception" date={invitation.reception_date} time={invitation.reception_time} venue={invitation.reception_venue} address={invitation.reception_address} maps={invitation.reception_maps}/></div></div></section></MotionSection>}
function LiveStream({invitation}:TemplateProps){const u=invitation.live_stream_url?.trim(),demo=invitation.is_demo; if(!u&&!demo)return null;return <MotionSection><section className="relative z-10 bg-[#dfe4e8] px-5 py-20 text-[#1c2b42] sm:px-8"><div className="mx-auto max-w-4xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">For guests afar</p><h2 className="mt-4 font-serif text-5xl">{invitation.live_stream_title||'The ceremony, live.'}</h2><div className="mt-10 grid aspect-video place-items-center border border-[#8fa0b5] bg-[#1c2b42] text-[#fbfaf6]"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full border border-white/40 text-xl">▶</span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.3em]">Live stream preview</p>{u&&<a href={u} target="_blank" className="mt-4 inline-block text-xs underline">Open livestream ↗</a>}</div></div></div></section></MotionSection>}
function Gallery({invitation}:TemplateProps){if(!S(invitation).gallery)return null;const u=invitation.gallery?.split(',').map((x:string)=>x.trim()).filter(Boolean)||[],p=['0% 0%','100% 0%','0% 100%','100% 100%'];return <MotionSection><section className="relative z-10 bg-[#fbfaf6] px-5 py-20 text-[#1c2b42] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">The album</p><h2 className="mt-4 font-serif text-5xl">A château in frames.</h2><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-4">{p.map((x,i)=><div key={x} className={`overflow-hidden bg-[#dfe4e8] ${i===0?'col-span-2 aspect-[4/3] md:col-span-2 md:row-span-2 md:aspect-auto':'aspect-[4/5]'}`} style={u[i]?undefined:{backgroundImage:`url('${chateauMedia.gallerySheet}')`,backgroundSize:'200% 200%',backgroundPosition:x}}>{u[i]&&<div className="relative h-full w-full"><Image src={u[i]} alt="Wedding moment" fill unoptimized className="object-cover"/></div>}</div>)}</div></div></section></MotionSection>}
function RSVP({invitation,guest}:TemplateProps){if(!S(invitation).rsvp)return null;return <MotionSection><section className="relative z-10 bg-[#1c2b42] px-5 py-20 text-[#fbfaf6] sm:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#a9b8c8]">Your reply</p><h2 className="mt-4 font-serif text-5xl">RSVP</h2></div>{invitation.is_demo?<p className="mt-10 border border-white/20 p-6 text-center text-sm">Live RSVP will appear on your client invitation.</p>:<div className="mt-12 grid gap-10 md:grid-cols-2"><RSVPForm invitationId={invitation.id} guest={guest??null}/><Guestbook invitationId={invitation.id}/></div>}</div></section></MotionSection>}
function Gift({invitation}:TemplateProps){if(!S(invitation).gift||!invitation.bank_account)return null;return <section className="relative z-10 bg-[#e9e5dc] px-5 py-20 text-[#1c2b42]"><div className="mx-auto max-w-xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#70869d]">With gratitude</p><h2 className="mt-4 font-serif text-5xl">A thoughtful gift.</h2><p className="mt-8 font-serif text-3xl">{invitation.bank_name}</p><p className="mt-3 text-xl">{invitation.bank_account}</p><div className="mt-6"><CopyButton text={invitation.bank_account}/></div></div></section>}
function Footer({invitation}:TemplateProps){return <footer className="relative z-10 bg-[#1c2b42] px-5 py-16 text-center text-[#fbfaf6]"><p className="text-[10px] font-bold uppercase tracking-[.42em] text-[#a9b8c8]">Merci</p><h2 className="mt-5 font-serif text-5xl">{N(invitation.groom_name)||'Étienne'} <span className="text-[#a9b8c8]">&amp;</span> {N(invitation.bride_name)||'Camille'}</h2><p className="mt-8 text-xs tracking-[.2em] text-white/50">AKSA DIGITAL STUDIO</p></footer>}
export const template009:InvitationTemplate={id:'template-009',name:'Midnight Cinema',description:'A cinematic premiere-night invitation with film posters, ticket stubs, and red velvet romance.',Cover,Hero,Couple,Story,Event:Celebration,LiveStream,Gallery,RSVP,Gift,Footer};
